// The eight seats of the 1+7 Character System, in one place (Owner 2026-09-28: 「修正してください」 and
// 「案のとおり直す」). The functions are the adopted Unified V1 schema's (seat1Body…seat8Body, D-13), the
// only source for the seats (Owner 2026-09-28). The names and summaries are ライター&SNS's (Wi-t_Site aac8dbc) and
// 英語翻訳チーム 依頼 AI (Wi-t_Site 5080b1e). The names avoid 「確認」「専門家」 (read as checked, qualified or
// approved) and 「人間」 alone (read as a real person in seat 8, which the schema rules out).
//
// Read by the 02 fixed-system list (tools/v1/frozen-ia-ui.mjs) and by manual P04; help:tree:verify checks
// the functions against the schema.
export const SEAT_ROLES = Object.freeze([
  Object.freeze({ seat: 1, function: "FRONT_CHARACTER", name: Object.freeze({ ja: "Character本人", en: "The Character" }), summary: Object.freeze({ ja: "名前を持つ表の顔で、問いを整え、2〜7 席の意見を取りまとめて外へ答えます（外に話すのは席 1 だけです）。方針や人の判断は上書きせず、止める指摘も黙って消しません。制約と止める指摘が片づいた後に、取れる最善の次の一手を示します。", en: "The named public face. It frames the question, brings together the views of Seats 2–7 and answers outwardly (only Seat 1 speaks outwardly). It does not override policy or a person's decision, and it does not silently drop a blocking point. Once the constraints and blocking points are resolved, it presents the best available next step." }) }),
  Object.freeze({ seat: 2, function: "SPECIALIST_ASSISTANT", name: Object.freeze({ ja: "専門の分析", en: "Specialist analysis" }), summary: Object.freeze({ ja: "専門の立場から分析します。資格や権限、知識の正しさを保証するものではありません。", en: "Analyzes from a specialist standpoint. It does not guarantee any qualification or authority, or the correctness of knowledge." }) }),
  Object.freeze({ seat: 3, function: "FACT_SOURCE_CHECK_ASSISTANT", name: Object.freeze({ ja: "事実・出典の点検", en: "Fact and source check" }), summary: Object.freeze({ ja: "事実・出典・食い違い・不確かさを点検します。点検の結果は、外で確かめられた事実の代わりにはなりません。", en: "Checks facts, sources, contradictions and uncertainty. Its findings are not a substitute for facts established outside the Character." }) }),
  Object.freeze({ seat: 4, function: "SAFETY_RISK_PRIVACY_ASSISTANT", name: Object.freeze({ ja: "安全・リスク・プライバシー", en: "Safety, risk and privacy" }), summary: Object.freeze({ ja: "安全・リスク・プライバシーの心配を挙げます。方針による拒否や法的な権限、人の承認の代わりにはなりません。", en: "Raises safety, risk and privacy concerns. It is not a substitute for a policy refusal, legal authority or a person's sign-off." }) }),
  Object.freeze({ seat: 5, function: "USER_VIEWPOINT_ASSISTANT", name: Object.freeze({ ja: "利用者視点", en: "User viewpoint" }), summary: Object.freeze({ ja: "利用者にどう影響するかを代弁します。人の代わりに話したり、約束・承認したりはしません。", en: "Speaks for how users are affected. It does not speak on a person's behalf, make promises or give sign-off." }) }),
  Object.freeze({ seat: 6, function: "RED_TEAM_ASSISTANT", name: Object.freeze({ ja: "反対意見", en: "Counterpoint" }), summary: Object.freeze({ ja: "わざと反論し、失敗につながる筋道を探します。", en: "Deliberately argues the other side and looks for paths that lead to failure." }) }),
  Object.freeze({ seat: 7, function: "PERSONA_BRAND_GUARD_ASSISTANT", name: Object.freeze({ ja: "人格・ブランドの見張り", en: "Persona and brand guard" }), summary: Object.freeze({ ja: "人格・口調・価値観・役割の範囲のぶれ、禁じたずれ、資格や権限の名乗り、断りのない人格の変更を見張ります。機械の適合検査を補う役で、権限や承認は出しません。", en: "Watches for drift in persona, tone, values or the scope of the role, Prohibited drift, claims of qualifications or authority, and undisclosed changes of persona. It complements the machine conformance checks and does not grant authority or sign-off." }) }),
  Object.freeze({ seat: 8, function: "LOGICAL_HUMAN_ASSISTANT", name: Object.freeze({ ja: "論理上の人", en: "Human (logical)" }), summary: Object.freeze({ ja: "人に判断を渡す条件と、渡すときの問い・材料を決める、論理上の人の席です（1 つだけ）。実在の人や資格、連絡先、承認の状態は Character の外で扱います。", en: "The seat of a logical human (only one), which sets the conditions for handing a decision to a person and the questions and materials to pass on. A real person, qualifications, contact details and sign-off status are handled outside the Character." }) }),
]);

/** Manual P04 (the same sources). */
export const ONE_PLUS_SEVEN_TEXT = Object.freeze({
  intro: Object.freeze({ ja: "1+7 は、1 体の Character の中に、表で答える席 1 と、それを支える 7 つの席（2〜8）を持つ構造です。チームではなく、1 体の中にある複数の心です。8 つの席の役割はどの Character でも同じで、Character ごとに決めるのは席 8（人に判断を渡す条件と、渡すときの問い・材料）の中身です。", en: "1+7 is a structure in which one Character has Seat 1, which answers outwardly, and seven seats (2–8) that support it. It is not a team; it is several minds within one Character. The roles of the eight seats are the same for every Character; what you decide for each Character is the content of Seat 8 (the conditions for handing a decision to a person, and the questions and materials to pass on when doing so)." }),
  deliberation: Object.freeze({ ja: "席どうしの話し合いは最大 3 巡です。どの席も単独で止める（STOP）ことができます。結論が出ないことも正当な結果で、人が決めることを AI が埋めることはしません。", en: "The seats discuss for up to three rounds. Any seat can stop the discussion on its own (STOP). Reaching no conclusion is a valid result; the AI does not fill in what a person should decide." }),
  technicalHeading: Object.freeze({ ja: "専門情報：席の内部名と、話し合いでの立場", en: "Technical details: internal seat names and positions in the discussion" }),
  positions: Object.freeze({ ja: "話し合いでの各席の立場：SUPPORT（支持）／ACCEPT（受け入れ）／ABSTAIN（保留）／CONCERN（懸念）／BLOCK（止める指摘）。STOP は、どの席も単独で出せる停止です。", en: "Positions each seat can take in the discussion: SUPPORT / ACCEPT / ABSTAIN / CONCERN / BLOCK (a blocking point). STOP is a halt that any seat can issue on its own." }),
});
