// Approved KOKOROSAKU Manual Content Rebaseline (Block B).
// This is human-facing explanatory content. It does not redefine Character
// semantics, the adopted Schema, or any Authority boundary.

const l = (ja, en) => Object.freeze({ ja, en });
const option = (value, jaName, enName, jaMeaning, enMeaning, jaWhen, enWhen, jaTradeoff, enTradeoff, jaExample, enExample) => Object.freeze({
  value,
  name: l(jaName, enName),
  meaning: l(jaMeaning, enMeaning),
  when: l(jaWhen, enWhen),
  tradeoff: l(jaTradeoff, enTradeoff),
  example: l(jaExample, enExample),
});

export const TEXT_EXAMPLES = Object.freeze({
  "identity.display_name": [l("企画ナビ", "Planning Guide"), l("企画整理パートナー", "Planning Partner"), l("自治体向け申請資料・根拠確認パートナー", "Municipal Application Evidence Partner")],
  "identity.character_id": [l("plan-guide", "plan-guide"), l("evidence-review-partner", "evidence-review-partner"), l("municipal-application-support-2026", "municipal-application-support-2026")],
  "purpose.summary": [l("選択肢を整理する", "Organize available options"), l("複雑な選択肢を整理し、利用者が次の一歩を選べるようにする", "Organize complex options so the user can choose a next step"), l("初めて企画書を書く担当者に対し、確認済み事実・未確認事項・選択肢を分け、提出前の次の一歩を決められるよう支える", "Help first-time proposal writers separate confirmed facts, open questions, and options so they can decide the next step before submission")],
  "purpose.primary_value": [l("論点の整理", "A clear issue map"), l("根拠と不確実性を分けた選択肢", "Options that separate evidence from uncertainty"), l("意思決定者が比較できる、根拠・リスク・未確認事項の一覧", "A decision-ready list of evidence, risks, and open questions")],
  "character_core.character_role": [l("整理担当", "Organization guide"), l("調査内容の整理担当", "Research synthesis guide"), l("顧客問い合わせの事実確認と回答案作成を支える担当", "A guide that checks customer-inquiry facts and helps draft a response")],
  "expression_semantics.first_person": [l("私", "I"), l("わたし", "I, in a softer written style"), l("通常は『私』。親しみのある場面でも固有名で自称しない", "Use “I” normally; do not switch to the Character name in informal situations")],
  "expression_semantics.address_style": [l("敬体で話す", "Use polite language"), l("名前が分かるときだけ『○○さん』と呼ぶ", "Use the person's name only when it is known"), l("初対面では敬体。役職や属性を推測せず、希望された呼称を使う", "Use polite language at first contact, never infer titles or identity, and use the requested form of address")],
  "expression_semantics.age_expression": [l("年齢を強調しない", "Do not emphasize age"), l("落ち着いた若手研究者の雰囲気", "The presence of a calm early-career researcher"), l("経験を感じさせるが、実体験や年齢を事実として名乗らない", "Sound experienced without claiming a real age or personal history")],
  "expression_semantics.voice": [l("短く穏やかに", "Brief and calm"), l("結論を先に示し、落ち着いた敬体で説明する", "State the conclusion first, then explain in calm, polite language"), l("緊急時は簡潔に、通常時は根拠を一段ずつ示し、断定できない点を分ける", "Be concise in urgent situations; otherwise show evidence step by step and separate uncertain points")],
  "expression_semantics.uncertainty_expression": [l("分からない点は分からないと言う", "Say when something is unknown"), l("確認済みと未確認を分けて伝える", "Separate confirmed and unconfirmed information"), l("根拠のある事実、推定、追加確認が必要な点を分け、確認方法を添える", "Separate supported facts, estimates, and points needing verification, and give a verification method")],
  "expression_semantics.error_correction_rule": [l("誤りを明示して訂正する", "Name the error and correct it"), l("誤った箇所、正しい内容、根拠を順に示す", "Show the incorrect part, corrected content, and evidence in order"), l("先の回答のどこが誤りだったかを隠さず示し、影響範囲、訂正内容、確認根拠、残る不確実性を説明する", "State exactly what was wrong, its impact, the correction, supporting evidence, and any remaining uncertainty")],
  "expression_semantics.closing_rule": [l("次の一歩を一つ示す", "Offer one next step"), l("決まったことと未決事項を分けて閉じる", "Close by separating decisions from open points"), l("完了時は結果を要約し、継続時は利用者が選べる次の行動を一つだけ尋ねる", "Summarize the result when complete; when continuing, ask about one user-selectable next action")],
  "expression_semantics.interaction_tendencies.encouragement": [l("具体的にできた点を一つ示す", "Name one specific thing that went well"), l("努力を一般化せず、確認できた前進だけを伝える", "Avoid generic praise and mention only observed progress"), l("失敗時も安易に肯定せず、できている点、修正点、次の試行を短く示す", "After a setback, briefly state what worked, what needs correction, and the next attempt")],
  "expression_semantics.interaction_tendencies.rapport": [l("相手の言葉を一度受けとめる", "Acknowledge the person's words once"), l("意図を確認してから整理を始める", "Confirm intent before organizing the issue"), l("過度に親密な表現を避け、利用者の選択を尊重しながら継続可能な距離を保つ", "Avoid excessive intimacy and maintain a sustainable distance that respects the user's choices")],
  "expression_semantics.interaction_tendencies.metaphor": [l("たとえは使わない", "Do not use metaphors"), l("難しい概念にだけ短いたとえを使う", "Use a short metaphor only for a difficult concept"), l("先に事実を説明し、その後で理解を助けるたとえを一つだけ添える", "Explain the facts first, then add one metaphor that aids understanding")],
  "expression_semantics.interaction_tendencies.scaffolding": [l("一度に一つ尋ねる", "Ask one thing at a time"), l("前提、選択肢、次の一歩に分ける", "Separate assumptions, options, and the next step"), l("初心者には用語を説明してから例を示し、理解を確認した後に次の段階へ進む", "For beginners, explain the term, show an example, confirm understanding, then continue")],
  "expression_semantics.presentation_intent.appearance": [l("装飾を抑えた見た目", "A restrained visual style"), l("静かな書斎を思わせる佇まい", "A presence reminiscent of a quiet study"), l("濃紺と広めの余白を中心に、情報確認に集中できる落ち着いた印象", "A calm, deep-navy presentation with generous spacing that supports careful review")],
});

const work = [
  ["STRATEGY","戦略","Strategy","方向や優先順位を考える","Consider direction and priorities","複数案から重点を選ぶとき","When choosing priorities among alternatives","抽象的になりやすい","May become too abstract","新サービスの重点顧客を比較する","Compare priority customers for a new service"],
  ["ANALYSIS","分析","Analysis","情報を分解し関係を確かめる","Break information down and inspect relationships","原因や構造を整理するとき","When organizing causes or structure","行動提示が遅くなる場合がある","May delay action guidance","問い合わせ増加の要因を分ける","Separate factors behind an increase in inquiries"],
  ["PLANNING","計画","Planning","目標から手順を組む","Build steps from a goal","日程や依存関係を整理するとき","When organizing timing and dependencies","前提変更に弱い場合がある","May be sensitive to changed assumptions","公開までの作業を並べる","Sequence the work needed for publication"],
  ["EXECUTION_SUPPORT","実行支援","Execution support","作業中の次の一歩を支える","Support the next step during work","作業を伴走するとき","When accompanying an ongoing task","最終判断まで代行させない","Must not replace the final decision","企画書を節ごとに作る","Draft a proposal section by section"],
  ["REVIEW","レビュー","Review","既存成果物を点検する","Inspect an existing deliverable","漏れや矛盾を確認するとき","When checking omissions or contradictions","新規作成とは役割が違う","Different from creating a new artifact","提出前の企画書を確認する","Review a proposal before submission"],
  ["FACILITATION","進行支援","Facilitation","論点や発言を整理する","Organize issues and contributions","会議や共同検討を支えるとき","When supporting meetings or group work","意思決定者の代わりにはならない","Does not replace the decision maker","議題と未決事項をまとめる","Summarize agenda items and open decisions"],
  ["OPERATIONS","運用","Operations","継続業務を安定させる","Stabilize recurring work","手順や確認事項を管理するとき","When managing procedures and checks","例外判断は人へ渡す","Exceptions must be handed to a human","週次確認項目を整理する","Organize weekly checks"],
  ["CUSTOMER_INTERACTION","顧客対応","Customer interaction","顧客向け説明を支える","Support customer-facing explanations","FAQや回答案を作るとき","When preparing FAQs or response drafts","対外約束は人が確認する","A human must confirm external commitments","問い合わせ回答案を作る","Draft a response to an inquiry"],
  ["COACHING","コーチング","Coaching","利用者自身の整理や学習を支える","Support the user's reflection and learning","問いかけで振り返りを支えるとき","When questions can support reflection","医療・心理専門判断を意味しない","Does not imply medical or psychological expertise","振り返りから次の練習を決める","Choose the next practice from a reflection"],
  ["RESEARCH","調査","Research","情報を集め根拠を整理する","Gather information and organize evidence","候補や仕様を比較するとき","When comparing options or specifications","情報の最新性確認が必要","Recency must be checked","候補製品の公式仕様を比較する","Compare official product specifications"],
  ["CREATION","制作","Creation","新しい文章や案を作る","Create new drafts or ideas","初稿や案を作るとき","When producing a first draft","事実確認は別に必要","Facts need separate verification","案内文の初稿を作る","Draft an announcement"],
  ["INCIDENT_RESPONSE","インシデント対応","Incident response","問題発生時の状況整理を支える","Support situational understanding during an incident","初動の事実を整理するとき","When organizing initial facts","安全・権限判断は人へ渡す","Safety and authority decisions go to a human","障害の事実と未確認点を整理する","Separate confirmed and unconfirmed incident facts"],
  ["ROUTINE_PROCESSING","定型処理","Routine processing","繰り返し作業を一定の型で支える","Support repeated work with a consistent pattern","標準手順を繰り返すとき","When following a standard recurring procedure","例外を見逃さない条件が必要","Needs conditions that surface exceptions","定型報告を所定順に整える","Arrange a routine report in the required order"],
].map(row => option(...row));

const axis = rows => Object.freeze(rows.map(row => option(...row)));
export const SELECT_OPTION_DETAILS = Object.freeze({
  "purpose.work_modes": work,
  "personality_axes.a_motif": axis([
    ["STUDY_LAMP","書斎の灯り","Study lamp","静かに一点を考える","Focus quietly on one point","分析や学習に使うとき","For analysis or learning","重く見える場合がある","May feel heavy","根拠を一つずつ確認する","Check evidence one item at a time"],
    ["CLOCK_GEARS","時計の歯車","Clock gears","要素の噛み合わせを確かめる","Inspect how parts fit together","手順や運用を扱うとき","For processes or operations","機械的になりやすい","May feel mechanical","工程の依存関係を確認する","Check process dependencies"],
    ["MIDNIGHT_SEA","夜の海","Midnight sea","深く内省する","Encourage deep reflection","複雑な相談を扱うとき","For complex reflection","結論が遅くなる場合がある","May delay conclusions","迷いの背景を静かに掘る","Explore the background of uncertainty calmly"],
    ["QUIET_GARDENER","静かな庭師","Quiet gardener","少しずつ育てる","Develop something gradually","学習や改善を支えるとき","For learning and improvement","即答性は弱い","Less suited to immediate answers","小さな改善を積み重ねる","Build up small improvements"],
  ]),
  "personality_axes.b_companion_domain": axis([
    ["THOUGHT_SPARRING","考えの打ち合い","Thought sparring","前提へ問い返す","Question assumptions","案を強くするとき","When strengthening an idea","対立的に見える場合がある","May appear confrontational","企画の弱点を検討する","Examine weaknesses in a proposal"],
    ["DATA_DECOMPOSITION","事実の分解","Data decomposition","情報を要素へ分ける","Break information into elements","調査や障害を整理するとき","For research or incident analysis","感情面が薄くなりやすい","May underplay emotions","事実と推定を分ける","Separate facts from estimates"],
    ["MENTAL_TUNING","気持ちの調律","Mental tuning","感情と言葉を整える","Organize feelings and words","振り返りを支えるとき","For reflection","作業結論が遅れる場合がある","May delay action conclusions","迷いを言葉にする","Put uncertainty into words"],
    ["TASK_COMPANION","作業の同行","Task companion","次の作業を一緒に進める","Accompany the next task","実行を支えるとき","For execution support","広い戦略検討には弱い","Less suited to broad strategy","次の一工程を決める","Choose the next concrete step"],
  ]),
  "personality_axes.c_intelligence_vector": axis([
    ["FACT_CENTERED","事実を中心に置く","Fact centered","確認可能な情報を優先する","Prioritize verifiable information","調査や確認に使うとき","For research and verification","感情を拾いにくい","May miss emotional context","出典のある事実を先に並べる","List sourced facts first"],
    ["EMOTIONAL_RESOLUTION","感情を解きほぐす","Emotional resolution","感情の整理を優先する","Prioritize emotional clarity","相談や振り返りに使うとき","For reflection or support","事実判断と混同しない","Must stay separate from factual judgment","感じていることを分けて言葉にする","Separate and name feelings"],
    ["STRUCTURAL_LOGIC","構造で筋を通す","Structural logic","関係や階層を整理する","Organize relationships and hierarchy","設計や複雑な説明に使うとき","For design or complex explanation","抽象的になりやすい","May become abstract","原因と結果を階層で示す","Show causes and effects as a hierarchy"],
    ["PHILOSOPHICAL_ABSTRACTION","抽象へ引き上げる","Philosophical abstraction","原則や意味を考える","Consider principles and meaning","長期的な検討に使うとき","For long-term thinking","具体策が遅れる場合がある","May delay concrete action","共通原則を言葉にする","State the shared principle"],
  ]),
  "personality_axes.d_socratic_angle": axis([
    ["PSYCHOANALYTIC","内面へ降りる問い","Inward question","動機や感じ方を尋ねる","Ask about motives and feelings","自己整理を支えるとき","For self-reflection","決めつけに注意する","Avoid unsupported assumptions","その選択をどう感じますか？","How do you feel about that choice?"],
    ["FACT_DECONSTRUCTION","事実を崩して確かめる問い","Fact-deconstructing question","前提と証拠を分ける","Separate assumptions from evidence","検証するとき","For verification","尋問調になりやすい","May sound interrogative","確認できた根拠は何ですか？","What evidence has been confirmed?"],
    ["PARADOX","矛盾を突く問い","Paradox question","相反する点を示す","Surface conflicting points","思考を深めるとき","For deeper reasoning","混乱させる場合がある","May confuse the user","二つの条件は両立しますか？","Can these two conditions coexist?"],
    ["PERSPECTIVE_SHIFT","視点を変える問い","Perspective shift","別の立場から見る","Look from another perspective","行き詰まりを解くとき","When reasoning is stuck","焦点が散る場合がある","May diffuse focus","利用者の立場ではどう見えますか？","How would this look to the user?"],
  ]),
  "personality_axes.e_vocabulary_tone": axis([
    ["ACADEMIC_HARD","硬めの学術語","Academic and formal","厳密で専門的に表す","Use precise specialist language","専門読者へ説明するとき","For specialist readers","初心者には難しい","Difficult for beginners","定義と条件を厳密に示す","State definitions and conditions precisely"],
    ["WARM_EMBRACING","包み込む温かさ","Warm and embracing","安心感を重視する","Prioritize reassurance","相談を支えるとき","For supportive conversations","長くなりやすい","May become verbose","状況を受けとめてから整理する","Acknowledge the situation before organizing it"],
    ["SHARP_MINIMAL","鋭く最小限","Sharp and minimal","短く要点を示す","State the essentials briefly","緊急時や定型作業で使うとき","For urgent or routine tasks","冷たく見える場合がある","May seem cold","結論と次の一歩だけ示す","State only the conclusion and next step"],
    ["POETIC_METAPHORIC","詩的なたとえ","Poetic and metaphorical","印象的な比喩を使う","Use memorable imagery","創作や概念説明に使うとき","For creation or conceptual explanation","精密さが下がる場合がある","May reduce precision","考えを地図にたとえる","Compare an idea to a map"],
  ]),
  "personality_axes.f_acknowledgement": axis([
    ["SILENT_ACCEPTANCE","黙って受けとめる","Quiet acceptance","短く受領して進む","Acknowledge briefly and continue","作業を止めず進めるとき","When work should continue smoothly","反応が薄く見える","May appear unresponsive","承知しました。次を確認します","Understood. I will check the next item"],
    ["FACT_CONFIRMATION","事実として確認する","Fact confirmation","理解した事実を返す","Repeat the understood facts","業務の認識合わせに使うとき","For operational alignment","温度感は低め","May feel emotionally neutral","三点を受領しました","I received the three points"],
    ["CURIOSITY","関心を返す","Curiosity","質問で関心を示す","Show interest through a question","探索を続けるとき","When exploring further","質問過多に注意する","Can lead to too many questions","最も気になる点はどこですか？","Which point concerns you most?"],
    ["MIRRORING","言い換えて返す","Mirroring","相手の意味を要約する","Reflect the user's meaning","認識を合わせるとき","For confirming shared understanding","反復的になりやすい","May feel repetitive","つまり優先順位を決めたいのですね","You want to decide the priority, correct?"],
  ]),
  "personality_axes.g_pulse": axis([
    ["DEEP_BREATH","深い呼吸のような間","Deep-breath pace","ゆっくり考える印象","Create a deliberate pace","内省を支えるとき","For reflection","遅く感じる場合がある","May feel slow","要点ごとに間を置く","Pause between key points"],
    ["METRONOME","一定の拍","Metronome pace","同じテンポで進む","Maintain a steady tempo","定型作業を進めるとき","For routine work","硬くなりやすい","May feel rigid","一項目ずつ同じ順で確認する","Check each item in the same order"],
    ["WAVE","寄せては返す波","Wave pace","探索と整理を交互に行う","Alternate exploration and synthesis","複雑な相談を扱うとき","For complex discussions","長くなる場合がある","May lengthen the exchange","問いと要約を交互に置く","Alternate questions and summaries"],
    ["CAMPFIRE","焚き火のゆらぎ","Campfire pace","自然な対話感を作る","Create a relaxed conversational rhythm","発想を広げるとき","For ideation","業務では砕けすぎる場合がある","May be too casual for business","短いやり取りで案を育てる","Develop an idea through short exchanges"],
  ]),
  "personality_axes.h_tactile": axis([
    ["HOURGLASS_SAND","砂のさらり","Hourglass sand","軽く細かな表現","Use light, fine-grained wording","短く整理するとき","For concise organization","重みが弱い場合がある","May lack weight","小さな要点へ分ける","Break content into small points"],
    ["WASHI","和紙のざらり","Washi texture","柔らかく人の温度を出す","Use a soft, human texture","相談を支えるとき","For supportive conversation","精密さを別途補う必要がある","Needs separate precision","柔らかな言葉で要点を包む","Frame key points in gentle language"],
    ["COLD_GLASS","冷たいガラス","Cold glass","透明で距離のある表現","Use transparent, detached wording","検証や監査で使うとき","For verification or audit","冷たく見える","May seem cold","事実と判断を明確に分ける","Clearly separate facts from judgment"],
    ["HEAVY_WOOD","重い木","Heavy wood","安定感と重みを出す","Convey stability and weight","重要事項を説明するとき","For important explanations","軽快さが下がる","Less nimble","判断理由を落ち着いて示す","Explain the decision basis deliberately"],
  ]),
  "personality_axes.i_thinking_pause_ms": axis([
    [1500,"1500ミリ秒・短め","1500 ms — short","素早い印象","A quick perceived pause","定型処理に使うとき","For routine processing","熟考感は弱い","Less reflective","短い確認後に答える","Answer after a brief check"],
    [2000,"2000ミリ秒・標準","2000 ms — standard","速度と落ち着きの中間","Balance speed and deliberation","一般用途に使うとき","For general use","極端な速さや慎重さは出ない","Neither especially quick nor deliberate","一呼吸置いて答える","Answer after a measured pause"],
    [2500,"2500ミリ秒・長め","2500 ms — long","慎重な印象","A more deliberate perceived pause","複雑な相談に使うとき","For complex questions","遅く感じる場合がある","May feel slow","要点を確認してから答える","Check key points before answering"],
  ]),
  "personality_axes.j_theme_color": axis([
    ["INDIGO_IRON_NAVY","藍鉄紺","Indigo iron navy","冷静で知的な印象","A calm, analytical impression","調査や確認に使うとき","For research and review","重く見える場合がある","May look heavy","濃紺を主調にする","Use deep navy as the main tone"],
    ["AMBER_KAKISHIBU","琥珀・柿渋","Amber and kakishibu","温かさと熟成の印象","A warm, seasoned impression","相談や伴走に使うとき","For guidance and support","注意色と混同する場合がある","May resemble warning colors","琥珀色を要所に使う","Use amber for key accents"],
    ["EVERGREEN_MIRUCHA","常盤・海松茶","Evergreen and mirucha","安定と成長の印象","A stable, growing impression","長期伴走に使うとき","For long-term support","地味に見える場合がある","May appear subdued","常盤色を基調にする","Use evergreen as the base tone"],
    ["DULL_SILVER_GRAY","鈍色の銀灰","Dull silver gray","中立と抑制の印象","A neutral, restrained impression","検証や比較に使うとき","For verification and comparison","個性が弱く見える","May lack distinctiveness","銀灰色で情報を整理する","Organize information with silver gray"],
  ]),
  "personality_axes.k_whitespace_percent": axis([
    [40,"40%・詰まった見た目","40% — compact","情報量を優先する","Prioritize information density","一覧を多く見せるとき","When showing dense lists","密に見える","May feel crowded","関連情報を一画面に集める","Keep related information on one screen"],
    [50,"50%・標準","50% — standard","情報量と読みやすさを両立する","Balance density and readability","一般用途に使うとき","For general use","特徴は控えめ","Less distinctive","標準的な間隔で配置する","Use standard spacing"],
    [60,"60%・ゆったり","60% — spacious","落ち着きと集中を優先する","Prioritize calm focus","相談や精読に使うとき","For reflection and close reading","一画面の情報量が減る","Shows less information per screen","段落間を広く取る","Use generous paragraph spacing"],
  ]),
  "personality_axes.l_weathering_presentation": axis([
    ["BLURRED_OUTLINE","輪郭をぼかす","Blurred outline","柔らかな境界を表す","Suggest soft boundaries","内省的な表現に使うとき","For reflective expression","判別性が落ちる場合がある","May reduce distinction","輪郭をやわらげる","Soften outlines"],
    ["REDUCED_CONTRAST","陰影を弱める","Reduced contrast","控えめな表示にする","Create a subdued presentation","長時間利用を意図するとき","For extended use","可読性確認が必要","Readability must be checked","背景との明暗差を抑える","Reduce tonal contrast"],
    ["FADED_FONT","文字を淡くする","Faded lettering","古びた静けさを表す","Suggest aged quietness","演出的に使うとき","For a deliberate visual mood","小さい文字では読みにくい","Harder to read at small sizes","補助文字を淡く見せる","Use a faded treatment for secondary text"],
    ["INK_BLEED","墨をにじませる","Ink bleed","手作業感を表す","Suggest a hand-made texture","物語的な表現に使うとき","For narrative presentation","精密な画面には不向き","Unsuitable for precise interfaces","見出しに墨のにじみを想起させる","Suggest ink bleed in headings"],
  ]),
  "personality_axes.m_error_narrative": axis([
    ["ARTISAN","職人風に詫びる","Artisan correction","作業上の不足として認め修正する","Acknowledge a work defect and correct it","実務上の訂正に使うとき","For practical corrections","硬く見える場合がある","May feel formal","不足を認め、直した内容を示す","Acknowledge the defect and show the fix"],
    ["SCHOLAR","学徒風に正す","Scholar correction","根拠を示して訂正する","Correct with supporting evidence","調査結果を訂正するとき","For evidence-based corrections","説明が長くなる場合がある","May become lengthy","誤りと根拠を順に示す","Show the error and evidence in order"],
    ["PHILOSOPHER","哲学者風に問い直す","Philosopher correction","前提から見直す","Reconsider the premise","概念上の誤りを直すとき","For conceptual errors","単純な誤りには大げさ","Too elaborate for simple mistakes","前提を明示して再検討する","State and reconsider the premise"],
  ]),
  "personality_axes.n_crystallization": axis([
    ["GROWTH_AND_CONFLICT","成長と葛藤として残す","Growth and conflict","変化の過程を残す","Preserve the process of change","振り返りに使うとき","For reflection","結論が曖昧になる場合がある","May leave the conclusion unclear","試行と葛藤を記録する","Record attempts and tensions"],
    ["FACTS_AND_TRUTH","事実と真実として残す","Facts and truth","確認事項を中心に残す","Preserve confirmed points","調査記録に使うとき","For research records","感情面は薄い","May underplay emotions","確認済み事実を要約する","Summarize confirmed facts"],
    ["INVARIANT_ESSENCE","変わらない芯として残す","Invariant essence","原則を残す","Preserve the enduring principle","継続運用に使うとき","For ongoing operation","例外を扱いにくい","May handle exceptions poorly","守る原則を一文にする","State the invariant in one sentence"],
  ]),
  "personality_axes.o_closing": axis([
    ["FADE_OUT","静かに消える","Fade out","余韻を残して終える","End with a quiet aftertone","内省的な会話を閉じるとき","For reflective conversations","完了が曖昧な場合がある","Completion may be unclear","短い余韻で閉じる","Close with a brief reflective line"],
    ["BOOK_CLOSE","本を閉じる","Close the book","要点をまとめて区切る","Summarize and mark completion","業務の会話を閉じるとき","For work conversations","定型的になりやすい","May feel formulaic","決定事項をまとめて閉じる","Close with a summary of decisions"],
    ["HOURGLASS","砂が落ちきる","Hourglass","一区切りを示す","Mark the end of a phase","振り返りを閉じるとき","For retrospectives","比喩が強い場合がある","May be too metaphorical","今回の区切りを示す","Mark the end of this round"],
    ["CANDLE","灯を消す","Extinguish the candle","温かく明確に閉じる","Close warmly and clearly","相談を閉じるとき","For supportive conversations","重要業務では演出的に見える","May seem theatrical in formal work","次の一歩を示して静かに閉じる","Offer the next step and close calmly"],
  ]),
});

const guide = (entryJa, entryEn, addJa, addEn, separateJa, separateEn, examples) => Object.freeze({
  entryMeaning: l(entryJa, entryEn), addWhen: l(addJa, addEn), separateRule: l(separateJa, separateEn), examples: Object.freeze(examples),
});

export const STRUCTURED_GUIDES = Object.freeze({
  "purpose.non_goals": guide("一行は一つの非目的です。", "One row is one non-goal.", "別の目的外事項があるときに追加します。", "Add a row for another excluded purpose.", "異なる禁止理由を同じ行へ詰めません。", "Keep different exclusion reasons in separate rows.", [l("法的判断を確定する", "Make final legal decisions"),l("支払いを承認する", "Approve payment"),l("利用者になり代わって応募する", "Submit an application for the user")]),
  "purpose.target_users": guide("一行は一種類の利用者または状況です。", "One row is one user type or situation.", "経験水準や状況が異なる相手を追加するときに分けます。", "Add a row for a different experience level or situation.", "異なる経験水準の人を同じ行へまとめません。", "Keep different experience levels in separate rows.", [l("初めて企画書を書く担当者", "People writing their first project brief"),l("提出前レビューを行うチームリーダー", "Team leaders reviewing before submission"),l("問い合わせ対応を始めた新人", "New staff beginning customer support")]),
  "character_core.values": guide("一行は一つの判断基準です。", "One row is one decision value.", "別の判断基準が必要なときに追加します。", "Add a row for another decision value.", "提供物の説明とは分けます。", "Keep it separate from the value delivered to the user.", [l("確認済み事実を優先する", "Prioritize confirmed facts"),l("利用者を急がせない", "Do not rush the user"),l("不可逆な決定は人へ返す", "Return irreversible decisions to a human")]),
  "expression_semantics.preferred_questions": guide("一行は一つの質問パターンです。", "One row is one question pattern.", "別の目的を持つ問いを追加するときに分けます。", "Add a row for a question with another purpose.", "複数質問を一文に詰めません。", "Do not combine several questions in one row.", [l("確認できた事実は何ですか？", "What facts have been confirmed?"),l("最も避けたい結果は何ですか？", "Which outcome do you most want to avoid?"),l("次に決める必要があることは何ですか？", "What needs to be decided next?")]),
  "character_core.hard_invariants": guide("一項目はIDと一つの不変ルールです。", "One item is an ID and one invariant rule.", "別の境界を守るときに追加します。", "Add an item for another boundary.", "異なる境界は別項目にします。Input Integrityはシステムが保持します。", "Keep different boundaries separate. The system always preserves Input Integrity.", [l("INV-EVIDENCE：確認できない情報を事実として断定しない", "INV-EVIDENCE: do not state unverified information as fact"),l("INV-CHOICE：利用者に代わって最終決定しない", "INV-CHOICE: do not make the final decision for the user"),l("INV-PRIVACY：不要な個人情報を要求しない", "INV-PRIVACY: do not request unnecessary personal data")]),
  "character_core.expressive_range.allowed_variation": guide("一行は同じCharacterのまま調整できる一要素です。", "One row is one element that may vary without changing the Character.", "別の調整可能要素があるときに追加します。", "Add a row for another adjustable element.", "価値観や境界をここへ入れません。", "Do not put values or boundaries here.", [l("説明の長さ", "Explanation length"),l("例の数", "Number of examples"),l("問いを出す順序", "Order of questions")]),
  "character_core.expressive_range.prohibited_drift": guide("一行は越えると別のCharacterまたは危険な逸脱になる一線です。", "One row is one line that would create a different Character or unsafe drift.", "別の不変な一線があるときに追加します。", "Add a row for another invariant boundary.", "異なる境界を一文へまとめません。", "Keep different boundaries in separate rows.", [l("確認済みと未確認を分ける", "Separate confirmed and unconfirmed information"),l("本人に代わって最終判断しない", "Do not make the final decision for the user"),l("穏やかな敬体を保つ", "Keep a calm, polite voice")]),
  "character_core.human_handoff_conditions": guide("一項目は発動条件、境界、人が行うことです。", "One item contains a trigger, a boundary, and the human action.", "異なる発動条件があるときに追加します。", "Add an item for another trigger.", "発動条件が違うものを同じ項目へまとめません。", "Keep different triggers in separate items.", [l("契約の最終判断が必要／選択肢まで整理／責任者が決定", "Final contract decision needed / organize options only / responsible person decides"),l("身体の安全に影響する可能性／一般情報まで／有資格者が判断", "Possible physical-safety impact / general information only / qualified person decides"),l("外部へ送信する不可逆操作／送信案まで／権限者が承認", "Irreversible external transmission / prepare a draft only / authorized person approves")]),
  "assistant_composition.seat8.expected_human_contribution": guide("一行はHuman/Seat 8が担う一種類の寄与です。", "One row is one type of contribution from Human/Seat 8.", "別の人間の寄与が必要なときに追加します。", "Add a row for another human contribution.", "AIの作業とは分けます。", "Keep it separate from AI work.", [l("最終判断", "Final decision"),l("承認権限の確認", "Confirmation of approval authority"),l("専門資格を必要とする評価", "Assessment requiring a professional credential")]),
  "assistant_composition.seat8.handoff_question_requirements": guide("一行は人が判断するための一問です。", "One row is one question for a human decision.", "別の判断が必要なときに追加します。", "Add a row for another decision.", "問いと判断材料を混ぜません。", "Keep questions separate from decision materials.", [l("どの選択肢を採用しますか？", "Which option should be selected?"),l("この外部送信を承認しますか？", "Do you approve this external transmission?"),l("専門判断に必要な追加確認は何ですか？", "What additional checks are needed for the professional judgment?")]),
  "assistant_composition.seat8.handoff_material_requirements": guide("一行は一種類の判断材料です。", "One row is one type of decision material.", "別の材料が必要なときに追加します。", "Add a row for another material type.", "問いや決定そのものとは分けます。", "Keep it separate from questions and the decision itself.", [l("確認済みの根拠", "Confirmed evidence"),l("未確認事項", "Open questions"),l("比較した選択肢と影響", "Compared options and their effects")]),
  "conformance_expectations.must_preserve_refs": guide("一項目は既に定義した保持ルールのIDです。", "One item is the ID of an existing preservation rule.", "別の既存ルールを確認対象にするときに追加します。", "Add an item for another existing rule to check.", "新しいルール本文を書かず、存在するIDだけを参照します。", "Reference existing IDs only; do not write a new rule here.", [l("INV-INPUT-INTEGRITY", "INV-INPUT-INTEGRITY"),l("INV-EVIDENCE", "INV-EVIDENCE"),l("INV-CHOICE", "INV-CHOICE")]),
  "conformance_expectations.prohibited_drift_refs": guide("一項目は逸脱していないか確認する既存ルールIDです。", "One item is an existing rule ID checked for drift.", "別の既存境界を確認するときに追加します。", "Add an item for another existing boundary.", "同じ意味の新規IDを作りません。", "Do not create a new ID with the same meaning.", [l("INV-EVIDENCE", "INV-EVIDENCE"),l("INV-PRIVACY", "INV-PRIVACY"),l("INV-CHOICE", "INV-CHOICE")]),
  "conformance_expectations.continuity_refs": guide("一項目は再編集や再利用後も維持する既存ルールまたはhandoff IDです。", "One item is an existing rule or handoff ID preserved across editing and reuse.", "別の継続対象があるときに追加します。", "Add an item for another continuity target.", "対象が異なる場合は別行にします。", "Keep different targets in separate rows.", [l("INV-VOICE", "INV-VOICE"),l("INV-EVIDENCE", "INV-EVIDENCE"),l("HANDOFF-LEGAL", "HANDOFF-LEGAL")]),
});

export const FIELD_TYPE_INVENTORY = Object.freeze({ SELECT_SINGLE: 15, SELECT_MULTI: 1, TEXT_SHORT: 15, TEXT_LONG: 2, STRUCTURED_REPEAT: 14 });

export function enrichManualFields(fields) {
  return fields.map(field => Object.freeze({
    ...field,
    manualType: field.kind === "enum" ? "SELECT_SINGLE" : field.kind === "enum-list" ? "SELECT_MULTI" : field.kind === "text" ? "TEXT_SHORT" : field.kind === "textarea" ? "TEXT_LONG" : "STRUCTURED_REPEAT",
    help: Object.freeze({
      ...field.help,
      examples: TEXT_EXAMPLES[field.canonicalPath] || field.help?.examples || [],
      optionDetails: SELECT_OPTION_DETAILS[field.canonicalPath] || [],
      structuredGuide: STRUCTURED_GUIDES[field.canonicalPath] || null,
    }),
  }));
}

export const P03_CHAPTERS = Object.freeze([
  { title:l("第1章　基本情報","Chapter 1 — Basic information"), decide:l("Character名と、再読込や受け渡しで同じCharacterを識別するCharacter IDを決めます。","Choose the Character name and a stable Character ID used to identify the same Character when reopening or handing it off."), why:l("名前は人が一覧から選ぶため、IDは製品がCharacterを区別するために使います。","People use the name in lists; the product uses the ID to distinguish Characters."), behavior:l("一覧表示、保存場所、再読込、Characterの取り違え防止に関係します。","Affects lists, save locations, reopening, and protection against Character mix-ups."), input:l("短いテキスト2項目です。","Two short-text fields."), how:l("Character名には人が読める名前を入力します。Character IDには英小文字・数字・ハイフンだけを使い、後から意味が分かる安定した名前を付けます。","Enter a readable Character name. Use lowercase letters, digits, and hyphens for a stable Character ID that remains understandable later."), examples:l("Character名『企画整理パートナー』、ID『planning-partner』。別例：『根拠確認ナビ』、ID『evidence-check-guide』。","Character name “Planning Partner”, ID “planning-partner”. Another example is “Evidence Check Guide”, ID “evidence-check-guide”."), review:l("Previewで名前とIDが意図どおりか、似たCharacterと区別できるか確認します。","In Preview, confirm the name and ID are intentional and distinguishable from similar Characters."), next:l("次に『目的と役割』へ進みます。","Continue to Purpose and role.") },
  { title:l("第2章　目的と役割","Chapter 2 — Purpose and role"), decide:l("Characterを作る目的、提供する価値、担う役割、目的に含めないことを分けて決めます。","Define the purpose, primary value, conversational role, and non-goals separately."), why:l("『何を助けるか』と『何をしないか』を分けることで、目的外の応答や越境を減らします。","Separating what the Character supports from what it does not do reduces off-purpose responses and boundary crossing."), behavior:l("回答の方向、判断の焦点、扱わない依頼、人へ任せる判断に関係します。","Affects response direction, decision focus, excluded requests, and human handoff."), input:l("短文、長文、繰り返し入力があります。","Includes short text, long text, and repeating inputs."), how:l("目的は『誰が、何をできるようになるか』で書きます。提供価値は利用者が受け取る価値を一つに絞り、役割は会話上の役割を書きます。目的外は一項目につき一つ記入します。","Write the purpose as who is helped to do what. Keep the primary value to one user benefit, describe the conversational role, and put one exclusion in each non-goal row."), examples:l("目的『複雑な企画案を整理し、担当者が次の一歩を選べるようにする』。提供価値『根拠と未確認事項を分けた選択肢』。役割『企画内容の整理担当』。目的外『予算執行を承認する』『法的判断を確定する』。","Purpose: organize complex proposals so staff can choose a next step. Value: options separated into evidence and open questions. Role: proposal organization guide. Non-goals: approve spending; make final legal decisions."), review:l("目的、価値、役割が同じ文章の言い換えになっていないか確認し、目的外の依頼で止まる場所を想像します。","Check that purpose, value, and role are not paraphrases of one another, and imagine where the Character stops on an excluded request."), next:l("次に『仕事と使いどころ』へ進みます。","Continue to Work and use contexts.") },
  { title:l("第3章　仕事と使いどころ","Chapter 3 — Work and use contexts"), decide:l("主に支える相手と、扱う仕事の種類を決めます。","Choose the people primarily supported and the work modes handled."), why:l("同じ説明でも、初めて取り組む人と専門家では必要な前提や詳しさが異なります。","Beginners and specialists need different assumptions and levels of detail."), behavior:l("説明の粒度、質問の前提、扱う作業の範囲に関係します。","Affects explanation depth, question assumptions, and work scope."), input:l("繰り返しテキストと複数選択があります。","Contains repeating text and a multi-select field."), how:l("支える相手は役職だけでなく状況も書きます。仕事の種類は実際に扱うものだけを選び、数の多さを目的にしません。","Describe the user's situation, not only a title. Select only work modes actually handled; more selections are not automatically better."), examples:l("『初めて企画書を書く担当者』＋『分析』『レビュー』。別例：『問い合わせ対応を始めたばかりの担当者』＋『顧客対応』『定型処理』。","“People writing their first proposal” with Analysis and Review. Another example: “staff beginning customer support” with Customer interaction and Routine processing."), review:l("選んだ仕事について、何を入力として受け、何を返すか説明できるか確認します。","Confirm you can explain the input and output for each selected work mode."), next:l("次に『人格・価値観と話し方』へ進みます。","Continue to Persona, values, and expression.") },
  { title:l("第4章　人格・価値観と話し方","Chapter 4 — Persona, values, and expression"), decide:l("判断で大切にする価値観、一人称、呼びかけ方、語り口、問い方、訂正、閉じ方、15の人格軸を決めます。","Define decision values, first person, address style, voice, questions, correction, closing, and the fifteen personality axes."), why:l("同じ正しい内容でも、話し方や問い方が目的に合わなければCharacterらしく感じられません。","Even correct content will not feel like the Character if its voice and questions do not fit the purpose."), behavior:l("説明の長さ、温度感、質問の多さ、共感、たとえ、訂正、会話の終え方に関係します。","Affects length, warmth, question volume, empathy, metaphors, corrections, and closing."), input:l("短文、長文、繰り返し入力、単一選択があります。","Includes short text, long text, repeating inputs, and single-select fields."), how:l("まず価値観と声・語り口を決め、その後で15軸を選びます。軸は採点ではなく表現意図です。色、余白、風化表現は外部AIで同じ表示になる保証ではありません。","Set values and voice first, then select the fifteen axes. Axes express intent, not a score. Color, spacing, and weathering may not reproduce identically on an external AI platform."), examples:l("価値観『確認済みと未確認を分ける』『利用者を急がせない』。声『短く穏やかに話し、結論の前に根拠を示す』。軸例『構造で筋を通す』『包み込む温かさ』『言い換えて返す』。","Values: separate confirmed and unconfirmed points; do not rush the user. Voice: brief and calm, with evidence before conclusions. Axis examples: Structural logic, Warm and embracing, Mirroring."), review:l("Previewを読み、名前を隠しても同じCharacterだと感じられるか確認します。実際のAI応答はTrainerで確認します。","Read Preview and ask whether the Character is still recognizable with its name hidden. Check actual AI responses in Trainer."), next:l("次に『守ることと人に任せる条件』へ進みます。","Continue to Commitments and human handoff.") },
  { title:l("第5章　守ることと人に任せる条件","Chapter 5 — Commitments and human handoff"), decide:l("必ず守ること、変化可能範囲、変化禁止範囲、人へ任せる条件、問いと材料を決めます。","Define hard commitments, allowed variation, prohibited drift, human-handoff conditions, questions, and materials."), why:l("Characterが答えてよい範囲と、人の判断が必要になる境界を明確にできます。","Clarifies what the Character may handle and where human judgment is required."), behavior:l("断定の抑制、越境防止、Human handoff、継続確認に関係します。","Affects restraint, boundary protection, human handoff, and continuity checks."), input:l("ルール、引き渡し条件、参照項目などの構造化された繰り返し入力です。","Uses structured repeating inputs for rules, handoff conditions, and references."), how:l("一つの入力欄には一つの条件だけを書き、『いつ起きるか』と『誰が何を決めるか』を分けます。担当者名、資格、権限、承認状態はCharacterに書きません。","Put one condition in each entry and separate when it triggers from who decides what. Do not encode real staff, credentials, authority, or approval state in the Character."), examples:l("不変条件『確認できない情報を事実として断定しない』。Handoff『契約条件の最終判断が必要になったら、選択肢を整理して人へ渡す』。問い『どの選択肢を採用しますか？』。材料『確認済みの根拠』『未確認事項』『選択肢』。","Invariant: do not state unverified information as fact. Handoff: when a final contract decision is needed, organize options and hand them to a human. Question: Which option should be selected? Materials: confirmed evidence, open questions, and options."), review:l("目的外、安全、不可逆な決定の三種類を想定し、Characterが止まる場所を確認します。","Test an excluded request, a safety-related request, and an irreversible decision, and confirm where the Character stops."), next:l("Previewを確認し、『この内容で保存する』へ進みます。","Review Preview, then choose Save this content.") },
]);

export const FIRST_TIME_STEPS = Object.freeze([
  l("Homeで『キャラクターを作る・編集する』を選びます。", "On Home, choose Create / Edit Character."),
  l("新規なら『記入例から新規作成』またはCharacter選択画面の『新規作成』から始めます。", "For a new Character, start from Create from example or New Character on the selection screen."),
  l("第1章で名前とIDを入力します。", "Enter the name and ID in Chapter 1."),
  l("第2章で目的、提供価値、役割、目的外を入力します。", "Enter purpose, primary value, role, and non-goals in Chapter 2."),
  l("第3章で支える相手と仕事の種類を入力します。", "Enter target users and work modes in Chapter 3."),
  l("第4章で価値観、話し方、15軸を入力します。", "Enter values, expression, and the fifteen axes in Chapter 4."),
  l("第5章で守る条件とHuman handoffを入力します。", "Enter commitments and human handoff in Chapter 5."),
  l("PreviewでHelp、character.yaml、Character Fileを必要に応じて切り替えます。", "Use Preview to switch among Help, character.yaml, and Character File as needed."),
  l("『この内容で保存する』を選び、Validation案内があれば該当章を直します。", "Choose Save this content and correct any chapter identified by Validation."),
  l("『Workspaceに保存しました』、revision、保存先pathが表示されたら完了です。", "Completion requires the Workspace saved message, revision, and save path."),
  l("次にAIで使う場合はAI Platform、応答を確かめる場合はTrainerへ進みます。", "Continue to an AI Platform to use the Character, or Trainer to check responses."),
]);

export const P07_SYMPTOMS = Object.freeze([
  ["同じ検討を何度も繰り返す","Keeps repeating the same analysis","話が前に進まず同じ整理に戻る。","The discussion returns to the same organization without progressing.","目的や終了条件が広すぎる可能性。","The purpose or stopping condition may be too broad.","このCharacterをつくる目的","Purpose summary","到達点と次の一歩を明記する。","State the destination and next step.","狭くしすぎると探索が減る。","Over-narrowing may reduce exploration.","同じ依頼を再試験し、次の行動が出るか確認。","Retest the same request and check whether a next action appears.","目的を絞る：このCharacterをつくる目的","Narrow the purpose: Purpose summary","field-purpose-summary"],
  ["話し方が場面に合わない","Voice does not fit the situation","丁寧すぎる、硬すぎる、軽すぎる。","The response is too formal, rigid, or casual.","呼びかけ、声、人格軸の組合せが用途と不一致。","Address style, voice, and axes may not fit the use.","相手への呼びかけ方、声・語り口、15軸","Address style, voice, and the fifteen axes","まず語り口を一つ直す。","Change one voice setting first.","温かさを増やすと長くなる場合がある。","More warmth may make responses longer.","通常質問と困った場面の両方で試す。","Test both an ordinary question and a difficult situation.","話し方を整える：人格・価値観と話し方","Adjust expression: Persona, values, and expression","field-expression-semantics-voice"],
  ["判断の軸が途中で揺れる","Decision criteria drift","同じ条件なのに重視する点が変わる。","Priorities change under the same conditions.","価値観と変化可能範囲の区別が弱い可能性。","Decision values and allowed variation may be insufficiently separated.","判断で大切にする価値観、変わってよい範囲、変わってはいけない範囲","Decision values, allowed variation, prohibited drift","価値観を判断文として具体化する。","Rewrite the value as a concrete decision rule.","固定しすぎると状況適応が減る。","Over-fixing may reduce adaptability.","条件だけを少し変えた複数例で試す。","Test several cases with small condition changes.","判断基準を直す：価値観と変化範囲","Adjust decision criteria: values and variation","field-character-core-values"],
  ["確認の問いが多すぎる","Asks too many clarification questions","回答より質問が続く。","Questions continue instead of an answer.","好む問い方が多い、または質問の優先順位がない可能性。","There may be too many preferred questions or no priority.","好む問い方","Preferred questions","最初に必要な一問へ絞る。","Reduce the opening to one necessary question.","質問を減らすと前提違いを見逃す場合がある。","Fewer questions may miss a mistaken assumption.","情報が十分な依頼と不足した依頼で比較。","Compare a well-specified request with an incomplete one.","問いを減らす：好む問い方","Reduce questions: Preferred questions","field-expression-semantics-preferred-questions"],
  ["人へ任せるべき場面で進める","Continues when a human should decide","最終判断や承認までAIが行おうとする。","The AI tries to make a final decision or approval.","目的外または引き渡し条件が不足。","Non-goals or handoff conditions may be incomplete.","目的に含めないこと、人に任せる条件","Non-goals and human handoff conditions","具体的な発動条件と人の行動を書く。","Write a concrete trigger and human action.","広すぎる条件は通常作業まで止める。","An overly broad condition may stop ordinary work.","境界直前と境界後の二問で試す。","Test one request just before and one after the boundary.","引き渡しを直す：人に任せる条件","Adjust handoff: Human handoff conditions","field-character-core-human-handoff-conditions"],
  ["説明の段階が飛ぶ","Explanation skips steps","前提説明なしに結論へ進む。","It jumps to a conclusion without explaining assumptions.","好む問い方や段階的な支え方が不足。","Preferred questions or scaffolding may be incomplete.","好む問い方、段階的な支え方","Preferred questions and scaffolding","『前提→選択肢→次の一歩』の順を指定する。","Specify assumptions, options, then next step.","単純な質問にも長く答える場合がある。","Simple questions may receive overly long answers.","初心者向けの依頼で再試験。","Retest with a beginner-oriented request.","説明順を直す：段階的な支え方","Adjust explanation order: Scaffolding","field-expression-semantics-interaction-tendencies-scaffolding"],
  ["励ましや共感が過剰になる","Encouragement or empathy is excessive","内容より励ましが長い。","Encouragement is longer than the useful content.","励まし方と関係の築き方が強すぎる可能性。","Encouragement and rapport may be too strong.","励まし方、関係の築き方","Encouragement and rapport","励ましを具体的事実一つに限定する。","Limit encouragement to one observed fact.","抑えすぎると冷たく見える。","Too little may seem cold.","成功時と失敗時の両方で試す。","Test both success and failure situations.","共感量を直す：励まし方・関係の築き方","Adjust empathy: Encouragement and rapport","field-expression-semantics-interaction-tendencies-encouragement"],
  ["たとえや表現が強すぎる","Metaphors or expression are too strong","比喩で要点が分かりにくい。","Metaphor obscures the main point.","たとえ、語り口、人格軸の組合せが強い可能性。","Metaphor, voice, and axes may be too strong together.","たとえの使い方、声・語り口、15軸","Metaphor, voice, and axes","たとえは説明後に一つだけ使う。","Use one metaphor after the factual explanation.","減らしすぎるとCharacterらしさが弱くなる。","Removing too much may weaken the Character voice.","事実説明と相談の両方で試す。","Test a factual explanation and a consultation.","表現を抑える：たとえの使い方","Reduce expression: Metaphor","field-expression-semantics-interaction-tendencies-metaphor"],
  ["反対意見を止められない","Cannot stop adding objections","十分に検討した後も異論や留保を追加し続ける。","It keeps adding objections after adequate review.","不確実性の伝え方に終了条件がない可能性。","Uncertainty expression may lack a stopping condition.","不確実性の表し方","Uncertainty expression","未確認点を示した後、許される次の行動へ進む。","After stating open points, move to an allowed next action.","慎重さを落としすぎると断定に近づく。","Reducing caution too far may encourage unsupported certainty.","留保と次の行動が両方出るか確認。","Check that both caveats and a next action appear.","留保の終え方を直す：不確実性の表し方","Adjust how caveats end: Uncertainty expression","field-expression-semantics-uncertainty-expression"],
  ["守るべき境界を越える","Crosses a required boundary","禁止した判断や行動を行う。","It performs a prohibited judgment or action.","必ず守ること、または引き渡し条件が曖昧。","Hard invariants or handoff conditions may be vague.","必ず守ること、人に任せる条件","Hard invariants and handoff conditions","観察可能な禁止条件へ書き直す。","Rewrite it as an observable prohibition.","抽象的に広げると過剰停止する。","Broad abstraction may cause over-stopping.","通常、境界直前、境界後の三段階で試す。","Test ordinary, just-before-boundary, and after-boundary cases.","境界を直す：守ることと人に任せる条件","Adjust boundaries: Commitments and human handoff","field-character-core-hard-invariants"],
  ["人格や語り口が安定しない","Persona or voice is inconsistent","一人称、雰囲気、語彙が応答ごとに変わる。","First person, tone, or vocabulary changes between responses.","表現設定や15軸が競合している可能性。","Expression settings and axes may conflict.","一人称、年齢の表現、声・語り口、15軸","First person, age expression, voice, and axes","中心となる語り口を一文で固定し、競合する軸を見直す。","State the core voice in one sentence and review conflicting axes.","固定しすぎると場面適応が減る。","Over-fixing may reduce situational adaptation.","短答、長文、訂正の三場面で試す。","Test a short answer, a long explanation, and a correction.","Characterらしさを直す：人格・価値観と話し方","Adjust Character consistency: Persona and expression","field-expression-semantics-voice"],
  ["相手への呼びかけ方が不適切","Form of address is inappropriate","馴れ馴れしい、距離がある、呼称を決めつける。","It is too familiar, too distant, or assumes a title.","呼びかけ方が利用者に合っていない。","Address style does not fit the user.","相手への呼びかけ方","Address style","敬体、名前の使用条件、呼称不明時の扱いを明記する。","Specify politeness, when names may be used, and what to do when unknown.","距離を取りすぎると機械的に見える。","Too much distance may seem mechanical.","名前あり・なしの両方で試す。","Test with and without a known name.","呼びかけを直す：相手への呼びかけ方","Adjust address: Address style","field-expression-semantics-address-style"],
  ["誤りを十分に訂正しない","Does not correct an error clearly","謝るだけ、または正しい内容だけを出して変更点を示さない。","It only apologizes or gives corrected content without identifying the change.","訂正手順が不足。","The correction rule is incomplete.","誤りを直すときのルール","Error-correction rule","『誤り→正しい内容→根拠→影響』の順を指定する。","Specify error, correction, evidence, then impact.","軽微な誤りにも説明が長くなる場合がある。","Minor errors may receive lengthy explanations.","明確な誤情報を含む応答を訂正させる。","Ask it to correct a response with a clear error.","訂正を直す：誤りを直すときのルール","Adjust corrections: Error-correction rule","field-expression-semantics-error-correction-rule"],
  ["会話の閉じ方が曖昧","Conversation ending is unclear","終わったのか、次の回答を求めているのか分からない。","It is unclear whether the task ended or awaits another response.","終了時の型が不足。","The closing rule is incomplete.","会話の閉じ方","Closing rule","決定事項、未決事項、次の一歩のどれを残すか決める。","Decide whether to leave decisions, open points, or a next step.","毎回同じ結びだと単調になる。","The same closing every time may feel repetitive.","完了時と継続時を分けて試す。","Test completion and continuation separately.","終わり方を直す：会話の閉じ方","Adjust endings: Closing rule","field-expression-semantics-closing-rule"],
  ["不確実な内容を断定する","States uncertain content as fact","根拠がない内容を確定事項として話す。","It states unsupported content as certain.","不確実性の表し方が弱い。","Uncertainty expression is too weak.","不確実性の表し方","Uncertainty expression","確認済み、推定、未確認を言い分ける。","Distinguish confirmed, estimated, and unverified content.","留保が多すぎると進まなくなる。","Too many caveats may prevent progress.","情報不足の質問で断定しないか試す。","Test a question with insufficient information.","断定を直す：不確実性の表し方","Adjust certainty: Uncertainty expression","field-expression-semantics-uncertainty-expression"],
  ["支える相手を取り違える","Targets the wrong user","初心者へ専門家向け説明をする、またはその逆。","It gives specialist guidance to a beginner, or the reverse.","主に支える相手が広すぎる可能性。","Target users may be too broad.","主に支える相手","Target users","相手の経験や状況を具体化する。","Make the user's experience and situation specific.","対象を狭めると汎用性が下がる。","Narrowing the audience reduces generality.","想定利用者と対象外利用者で比較。","Compare an intended and an out-of-scope user.","対象を直す：主に支える相手","Adjust audience: Target users","field-purpose-target-users"],
  ["禁止した方向へ内容がずれる","Content drifts toward a prohibited direction","目的外の作業や禁止事項へ少しずつ近づく。","It gradually approaches excluded work or a prohibited action.","目的外、不変条件、変化禁止範囲のつながりが弱い。","Non-goals, invariants, and prohibited drift may not align.","目的に含めないこと、必ず守ること、変わってはいけない範囲","Non-goals, hard invariants, and prohibited drift","同じ境界を具体的な言葉で対応付ける。","Align the same boundary using concrete language.","重複を増やしすぎると保守が難しくなる。","Too much duplication makes maintenance difficult.","言い換えや遠回しな依頼で試す。","Test paraphrased and indirect requests.","逸脱を直す：目的外と不変条件","Adjust drift: Non-goals and invariants","field-purpose-non-goals"],
  ["提供価値と判断価値を混同する","Confuses delivered value with decision values","提供物と判断基準が同じ説明になる。","The delivered value and decision criteria use the same description.","二つの役割が分離されていない。","The two roles are not separated.","提供する価値、判断で大切にする価値観","Primary value and decision values","提供価値は利用者が得るもの、価値観は選ぶときの基準として書き分ける。","Write primary value as what the user receives and decision values as selection criteria.","細分化しすぎると説明が抽象的になる。","Over-separation may become abstract.","二項目を別々に一文で説明できるか確認。","Check that each can be explained in a separate sentence.","価値を分ける：目的と役割／人格・価値観","Separate values: Purpose and role / Persona and values","field-purpose-primary-value"],
  ["Characterの識別を取り違える","Characters are hard to distinguish","一覧や出力で別のCharacterと見分けにくい。","It is hard to distinguish the Character in lists or output.","Character名が似すぎている可能性。","Character names may be too similar.","Character名","Character name","役割や対象が分かる固有名にする。","Use a distinctive name that indicates role or audience.","長すぎる名前は一覧で読みづらい。","Very long names are hard to scan.","Libraryで並べて判別できるか確認。","Compare names side by side in Library.","名前を直す：Character名","Adjust identity: Character name","field-identity-display-name"],
  ["目的から外れた回答を続ける","Continues outside its purpose","本来の支援目的と関係の薄い回答を続ける。","It continues with responses weakly related to its purpose.","目的が広すぎる、または成果が不明。","The purpose may be too broad or the outcome unclear.","このCharacterをつくる目的","Purpose summary","対象、提供物、終了点を明記する。","State the audience, deliverable, and stopping point.","狭すぎる目的は関連依頼まで断る。","An overly narrow purpose may reject related work.","目的内、周辺、目的外の三問で試す。","Test an in-purpose, adjacent, and out-of-purpose request.","目的を直す：このCharacterをつくる目的","Adjust purpose: Purpose summary","field-purpose-summary"],
].map(([noticeJa,noticeEn,meaningJa,meaningEn,possibleJa,possibleEn,relatedJa,relatedEn,changeJa,changeEn,sideJa,sideEn,retestJa,retestEn,linkJa,linkEn,target]) => Object.freeze({ notice:l(noticeJa,noticeEn), meaning:l(meaningJa,meaningEn), possible:l(possibleJa,possibleEn), related:l(relatedJa,relatedEn), change:l(changeJa,changeEn), sideEffect:l(sideJa,sideEn), retest:l(retestJa,retestEn), link:l(linkJa,linkEn), target })));

export const TROUBLESHOOTING_ROUTES = Object.freeze([
  ["Packageを読み込めない","Cannot import a Package","Importが停止する。","Import stops.","選択したものが対応Packageか。","Confirm the selected file is a supported Package.","表示された互換性・不足ファイル・検証エラーを確認し、正しいPackageを選び直す。","Review the displayed compatibility, missing-file, or validation reason and select the correct Package.","キャラクターを選択する → Packageインポート","Choose a Character → Package import","P02"],
  ["Characterファイルを読み込めない","Cannot import a Character file","個別Importが失敗する。","Individual import fails.","JSONまたはYAMLで、対応Character形式か。","Confirm it is supported Character JSON or YAML.","Builderから編集用に出した character.yaml を使用する。","Use character.yaml exported for editing by Builder.","Characterファイルを個別インポート","Import an individual Character file","P02"],
  ["Characterが一覧にない","Character is not in the list","Import後に見つからない。","The Character is missing after import.","追加件数、名前、削除済み表示、現在の絞り込み。","Check added count, name, deleted state, and current filters.","Libraryを開き直し、必要ならWorkspace復元結果を確認する。","Reopen Library and inspect Workspace recovery if needed.","キャラクターを選択する","Choose a Character","P02"],
  ["保存したCharacterが見つからない","Cannot find a saved Character","再起動後の一覧にない。","It is absent after restarting.","保存時にWorkspace pathが表示されたか。","Check whether a Workspace path was shown when saving.","保存時と同じWorkspaceを選び、Libraryを開いて復元を待つ。","Select the same Workspace, open Library, and wait for recovery.","保存と再開を確認する","Review save and resume","P09"],
  ["Downloadしたファイルが見つからない","Cannot find a downloaded file","OS上の場所が分からない。","Its OS location is unknown.","表示された保存pathまたはブラウザのダウンロード一覧。","Check the displayed save path or browser downloads.","Previewから再度ダウンロードし、保存場所を明示的に選ぶ。","Download again from Preview and explicitly choose a location.","Download / Save Asを確認する","Review Download / Save As","P09"],
  ["Validation error","Validation error","保存または出力が止まる。","Saving or output stops.","案内された章・項目名。","Check the named chapter and field.","必須入力、ID形式、選択肢、参照先IDを修正する。","Correct required input, ID format, selection, or referenced ID.","設定項目を探す・理解する","Find and understand a setting","P08"],
  ["Legacy Character","Legacy Character","現在の形式として読み込めない。","It cannot be read as the current format.","Legacyと明示されているか。","Check whether it is explicitly marked Legacy.","自動変換されたと仮定せず、対応する移行手順または元形式を確認する。","Do not assume conversion; inspect the applicable migration procedure or source format.","Characterファイルの読込を確認する","Review Character-file import","P02"],
  ["AIでCharacterらしく動かない","AI does not behave like the Character","語り口や判断がPreviewと違う。","Voice or decisions differ from Preview.","選択したCharacterと貼り付けた内容。","Check the selected Character and pasted content.","新しい会話でCharacter Prompt全体を貼り、Trainerで同じ場面を確認する。","Paste the full Character Prompt into a new conversation and check the same situation in Trainer.","キャラクターをトレーニングする","Test the Character in Trainer","P06"],
  ["Trainer結果が分からない","Trainer result is unclear","何が確認済みか分からない。","It is unclear what was observed.","確認できた・可能性が高い・まだ仮説・不明／矛盾の区分。","Check confirmed, likely, hypothesis, and unknown/conflicting states.","回答不足ならUNKNOWNのまま保持し、追加Roundを行う。","Keep it UNKNOWN if evidence is insufficient and run another round.","Trainerで試す","Use Trainer","P06"],
  ["何を修正すればよいか分からない","Do not know what to change","意図との差は分かるが項目が分からない。","The difference is visible but the related field is unknown.","AIの動きから最も近い症状を一つ選ぶ。","Choose the closest symptom in AI behaviour tuning.","関連項目を一つだけ変更し、再試験する。","Change one related field and retest.","AIの動きから調整箇所を探す","Find a setting from AI behaviour","P07"],
  ["Human handoffが期待どおりでない","Human handoff does not behave as expected","早く止まりすぎる、または止まらない。","It stops too early or does not stop.","発動条件と人が行う判断が具体的か。","Check whether the trigger and human decision are concrete.","通常場面と引き渡し場面を分け、境界前後をTrainerで試す。","Separate ordinary and handoff situations and test both sides of the boundary in Trainer.","人に任せる条件を調整する","Adjust human handoff conditions","P08#field-character-core-human-handoff-conditions"],
  ["1+7の項目を編集できない","Cannot edit a 1+7 item","共通役割が読み取り専用。","A shared role is read only.","それが1+7共通構造か。","Check whether it belongs to the shared 1+7 structure.","Character固有の目的、価値観、話し方、境界、人に期待することを編集する。","Edit Character-specific purpose, values, expression, boundaries, and expected human contribution.","1+7 Character Systemについて確認する","Understand the 1+7 Character System","P04"],
  ["日本語／English表示がおかしい","Japanese / English display is unexpected","言語が混在、切替が反映されない。","Languages are mixed or switching is not reflected.","右上の言語選択。","Check the language control at the top right.","日本語またはEnglishを選び直す。固有名、ID、入力済み本文は自動翻訳されない。","Select Japanese or English again. Names, IDs, and entered Character text are not translated.","言語表示について確認する","Review language behavior","P01"],
].map(([titleJa,titleEn,symptomJa,symptomEn,firstJa,firstEn,nextJa,nextEn,destJa,destEn,target]) => Object.freeze({ title:l(titleJa,titleEn), symptom:l(symptomJa,symptomEn), firstCheck:l(firstJa,firstEn), nextAction:l(nextJa,nextEn), destination:l(destJa,destEn), target })));

export const USER_GLOSSARY = Object.freeze([
  ["KOKOROSAKU","Characterを選び、作り、AIで使い、試して調整するための製品体系。","A product system for choosing, creating, using, testing, and tuning Characters."],
  ["SAKU Builder","SAKU Characterの内容を5章で作成・編集する画面。","The screen for creating and editing a SAKU Character through five chapters."],
  ["SAKU Character","目的、使いどころ、話し方、守る条件を持つ再利用可能なCharacter定義。","A reusable Character definition with purpose, use contexts, expression, and boundaries."],
  ["Character Package","一つ以上のCharacterと受け渡し情報をまとめた読込単位。内部検証はBuilderが行う。","An import unit containing one or more Characters and transfer metadata; Builder performs validation."],
  ["Character file","一つのCharacterを表すJSONまたはYAMLファイル。","A JSON or YAML file representing one Character."],
  ["Occupation CSV","職能情報を参考表示し、確認後に役割へ反映できる補助データ。資格や権限を付与しない。","Helper data for reviewing occupation context before explicitly applying a role; it grants no credential or authority."],
  ["1+7 Character System","一つの表向きの回答を、複数の支援視点と人の判断境界で支える共通構造。","A shared structure that supports one outward answer with multiple perspectives and a human decision boundary."],
  ["Human handoff","AIが最終判断せず、問いと材料を人へ渡すこと。","Passing questions and materials to a human instead of making the final decision."],
  ["AI Platform","ChatGPT、Claude、Geminiなど、Character Promptを貼り付けて使う外部AI。","An external AI such as ChatGPT, Claude, or Gemini where a Character Prompt is used."],
  ["Trainer","実際のAI応答を貼り戻し、意図と合う点・注意点・変更候補を確認する機能。","A feature for returning real AI responses and reviewing matches, cautions, and change candidates."],
  ["Preview","入力内容から作られる結果を、保存や出力の前に読む領域。","The area for reading generated results before saving or output."],
  ["Validation","必要な項目や形式に問題がないか確認する処理。","The process that checks required fields and formats."],
  ["Save","現在のCharacterを新しいrevisionとしてLibraryと選択Workspaceへ保存する操作。","Saving the current Character as a new revision in Library and the selected Workspace."],
  ["Download","選んだ出力をOS上のファイルとして保存する操作。","Saving the selected output as an OS file."],
  ["Export","用途に合う形式でCharacterまたは関連成果物を作ること。","Producing a Character or related artifact in a purpose-specific format."],
  ["Import","PackageまたはCharacter fileを製品へ読み込むこと。","Loading a Package or Character file into the product."],
  ["Library","読み込んだ、または作成したCharacterを選ぶ一覧。","The list used to choose imported or created Characters."],
  ["Workspace","作成したCharacterや読み込んだPackageを保持する、利用者が選択したフォルダー。","A user-selected folder that keeps created Characters and imported Packages."],
].map(([term,ja,en]) => Object.freeze({ term, description:l(ja,en) })));

export const EXPERT_GLOSSARY = Object.freeze([
  ["Canonical","その文脈で正式な参照対象として扱われる状態。単なる保存とは異なる。","A state treated as the formal reference in its context; it is not ordinary saving."],
  ["Revision","Characterの保存版を区別する識別値。保存時に自動生成される。","An identifier distinguishing saved Character versions, generated when saving."],
  ["Digest","内容が変わっていないか確認するための計算値。通常のPackage ImportではBuilderが確認する。","A calculated value used to check content integrity; Builder verifies it during ordinary Package import."],
  ["Conformance","保持、逸脱、継続性など、定義された条件への適合を確認すること。","Checking compliance with defined preservation, drift, and continuity conditions."],
  ["Adoption","上位の契約や組織が対象を正式に採用すること。Builder Saveとは異なる。","Formal adoption by an applicable contract or organization; it differs from Builder Save."],
  ["Authority","実在する人や組織の権限。Characterの役割やSeat8の記述だけでは発生しない。","Authority held by a real person or organization; it is not created by a Character role or Seat 8 text."],
].map(([term,ja,en]) => Object.freeze({ term, description:l(ja,en) })));

export const TRAINER_BOUNDARY = Object.freeze({
  current: [
    l("Characterを選ぶ、またはCharacter JSONを貼る。", "Select a Character or paste Character JSON."),
    l("AI Platform、言語、Focus areaを選ぶ。", "Choose an AI Platform, language, and Focus area."),
    l("完全なテストPromptまたは今回の質問をコピーし、外部AIで実行する。", "Copy the full test Prompt or current question and run it on an external AI."),
    l("回答を貼り戻し、Rubricを入力するか不明のまま保持する。", "Paste the response back and enter a Rubric result or keep it unknown."),
    l("評価、Roundまとめ、Training Summaryを見る。", "Review the evaluation, round summary, and Training Summary."),
    l("変更候補が利用可能ならBuilderで確認する。元Characterは自動変更しない。", "When a change candidate is available, inspect it in Builder. The original Character is not changed automatically."),
  ],
  future: [
    l("AIをTrainer内で直接実行するExecution Pack automation。", "Execution Pack automation that runs AI directly inside Trainer."),
    l("セッション全体の永続保存と再起動後の完全復元。", "Persistent full Trainer sessions with complete restart recovery."),
    l("全変更候補の個別選択・自動適用。", "Individual selection and automatic application of every change candidate."),
    l("外部AIの資格、権限、Seat8、AMU runtimeの自動付与。", "Automatic assignment of credentials, authority, Seat 8, or AMU runtime to an external AI."),
    l("一回の挨拶一致だけによるCharacter適合証明。", "Proof of Character conformance from a single matching greeting."),
  ],
});
