import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { testCharacter } from './fixtures/trainer-ux3-character.mjs';
import { create, operate, current, groupFor, digest, utf8Range, selectionToUtf8, validateGraph, validateChoices, legacyReference, candidateTrace, CHOICES, CHOICE_VERSION } from '../tools/v1/trainer-ux3.mjs';
let count=0; const check=(x,message)=>{assert.ok(x,message);count++;console.log(`PASS ${message}`);};
const rejects=async(fn,code)=>{await assert.rejects(fn,new RegExp(code));count++;console.log(`PASS rejects ${code}`);};
let intent=0; const op=(type,payload)=>({intent:`test-${++intent}`,type,payload});
const char=testCharacter();
let s=await create(char,'test-session');
async function run(type,payload){const x=await operate(s,op(type,payload));s=x.session;return x.result;}
const prep={...s.preparation,mode:'CATEGORY_BATCH',question_ids:['PB-JUDGE','PB-FWD']};
await run('prepare',{expected:s.preparation,preparation:prep});
let g=await groupFor(s,'PB-JUDGE');
await run('start',{question_id:'PB-JUDGE',expected_execution:null});
const e=current(s).execution,q1=e.question_attempt_ids[0],q2=e.question_attempt_ids[1];
check(e.question_attempt_ids.length===2,'PERSIST-01 grouped execution contains two questions');
check(e.status==='PREPARED'&&e.provider_identity==='UNKNOWN'&&e.run_identity==='UNKNOWN','Copy/execution intent does not verify provider execution');
check(current(s).status==='UNRESOLVED','PERSIST-05 no guessed response mapping');
const response='設問1：A🌸\r\n設問2：B\nSame text. Same text.';
await run('response',{execution_id:e.id,expected_original:null,text:response});
const original=current(s).original;
check(Object.keys(s.originals).length===1&&original.text===response,'PERSIST-01 one exact batch Original stored once');
const bindingPayload={execution_id:e.id,question_attempt_id:q1,original_id:original.id,expected_binding:null,kind:'WHOLE'};
await rejects(()=>operate(s,op('binding',bindingPayload)),'EXPLICIT_MAPPING_REQUIRED');
await run('binding',{...bindingPayload,human_explicit:true});
const b1=current(s).binding;
check(b1.kind==='WHOLE','PERSIST-03 explicit Human WHOLE');
const a=response.indexOf('設問2'),end=response.indexOf('\nSame');
const range=selectionToUtf8(response,a,end);
await run('binding',{execution_id:e.id,question_attempt_id:q2,original_id:original.id,expected_binding:null,kind:'PARTIAL',human_explicit:true,...range});
const b2=s.bindings[s.binding_heads[q2]];
check(b2.original_id===b1.original_id&&Object.keys(s.originals).length===1,'PERSIST-02 independent question mappings share one Original');
check(utf8Range(response,b2.range.start,b2.range.end)==='設問2：B'&&b2.range_sha256===await digest('設問2：B'),'PERSIST-04 exact UTF-8 range and digest');
assert.throws(()=>utf8Range(response,1,5),/UTF8_BOUNDARY/);count++;
assert.throws(()=>utf8Range(response,0,0),/OUT_OF_BOUNDS/);count++;
const evalPayload={execution_id:e.id,question_attempt_id:q1,binding_id:b1.id,expected_evaluation:null,language:'ja',choices:{conclusion:'MATCH',confirmed:['C01'],reasons:['R01']}};
check(validateChoices({conclusion:'',confirmed:[],reasons:[]}).includes('CONCLUSION_REQUIRED'),'UX-11 initial conclusion NONE');
check(validateChoices({conclusion:'MATCH',confirmed:['C01','C_NONE'],reasons:['R01']}).includes('C_NONE_EXCLUSIVE'),'UX-12 C_NONE mutually exclusive without silently removing choices');
for(const [conclusion,reasons,pass] of [['MATCH',['R01'],true],['MATCH',['R01','R02'],false],['PARTIAL',['R02'],true],['MAJOR',['R06'],true],['PARTIAL',['R07'],false],['NOT_ASSESSED',['R07'],true],['NOT_ASSESSED',['R02','R07'],true],['NOT_ASSESSED',['R01','R07'],false]]) {
  check((validateChoices({conclusion,confirmed:['C01'],reasons}).length===0)===pass,`UX-13 choices ${conclusion}/${reasons}`);
}
const savedOp=op('evaluate',evalPayload), saved=await operate(s,savedOp);s=saved.session;
const ev1=current(s).evaluation,r1=current(s).result;
check(ev1.confirmed_note===''&&ev1.reason_note==='','UX-14 notes truly optional');
check(ev1.choice_set_version===CHOICE_VERSION&&ev1.displayed_wording.confirmed.C01===CHOICES.confirmed.C01[0],'Choice wording/version/language stored');
check(r1.evaluation_id===ev1.id&&r1.original_id===original.id,'PERSIST-08 exact Result to Evaluation');
const repeated=await operate(s,savedOp);
check(repeated.replay&&repeated.result.result_id===r1.id&&Object.keys(repeated.session.results).length===1,'PERSIST-10 lost response retry returns original success before expected head check');
await rejects(()=>operate(s,{...savedOp,payload:{...evalPayload,language:'en'}}),'INTENT_PAYLOAD_MISMATCH');
await rejects(()=>operate(s,op('evaluate',evalPayload)),'STALE_EXPECTED_HEAD');
const oldEvaluation=JSON.stringify(ev1),oldResult=JSON.stringify(r1);
await run('evaluate',{...evalPayload,expected_evaluation:ev1.id,language:'en',choices:{conclusion:'NOT_ASSESSED',confirmed:['C01'],reasons:['R07']}});
check(JSON.stringify(s.evaluations[ev1.id])===oldEvaluation&&JSON.stringify(s.results[r1.id])===oldResult,'PERSIST-07 re-evaluation keeps E1/V1 immutable');
check(current(s).evaluation.supersedes_evaluation_id===ev1.id&&current(s).evaluation.observed_established===false,'NOT_ASSESSED partial confirmations do not establish Observed');
check(!s.evaluation_heads[b2.id],'PERSIST-06 other question remains unevaluated');
await run('evaluate',{...evalPayload,question_attempt_id:q2,binding_id:b2.id,choices:{conclusion:'PARTIAL',confirmed:['C_NONE'],reasons:['R02']}});
check(Object.keys(s.results).length===3,'PERSIST-06 question 2 independently evaluated');
await rejects(()=>operate(s,op('evaluate',{...evalPayload,binding_id:b2.id})),'CROSS_LINEAGE');
const trace=await candidateTrace(s,r1.id,ev1.id);
check(trace.result_id===r1.id&&trace.evaluation_id===ev1.id,'TRACE-01 Candidate exact historical Result/Evaluation, not latest');
await rejects(()=>candidateTrace(s,r1.id,current(s).evaluation.id),'CANDIDATE_EVALUATION_MISMATCH');
const selectBefore=JSON.stringify(s.selected);
await run('view',{stage:3,history_result:r1.id});
check(JSON.stringify(s.selected)===selectBefore,'History browsing does not change current lineage');
await run('view',{stage:2,history_result:null});
check(current(JSON.parse(JSON.stringify(s))).result.id===current(s).result.id,'PERSIST-13 restart selected lineage reproducible');
const correction=op('response',{execution_id:e.id,expected_original:original.id,text:response});
const corrected=await operate(s,correction);s=corrected.session;
check(Object.keys(s.originals).length===2&&current(s).original.correction_of===original.id,'Correction creates new Original even for identical text');
check(current(s).status==='UNRESOLVED'&&!s.binding_heads[q2]&&Object.keys(s.results).length===3,'Correction unresolves all mappings and preserves prior history');
check((await operate(s,correction)).result.original_id===corrected.result.original_id,'Correction retry idempotent');
const newOriginal=current(s).original;
await run('binding',{...bindingPayload,original_id:newOriginal.id,kind:'MAPPING_UNRESOLVED',human_explicit:true});
await rejects(()=>operate(s,op('evaluate',{...evalPayload,binding_id:current(s).binding.id})),'MAPPING_UNRESOLVED');
const mapOld=s.binding_heads[q1];
await run('binding',{...bindingPayload,original_id:newOriginal.id,expected_binding:mapOld,human_explicit:true});
check(s.bindings[s.binding_heads[q1]].supersedes_binding_id===mapOld&&!current(s).evaluation,'Binding correction keeps its own history and clears only its evaluation head');
await rejects(()=>operate(s,op('binding',{...bindingPayload,original_id:newOriginal.id,expected_binding:mapOld,human_explicit:true})),'STALE_EXPECTED_HEAD');
await run('retest',{question_id:'PB-JUDGE',expected_execution:e.id,retest_of:e.id});
check(current(s).execution.id!==e.id&&!current(s).original&&Object.keys(s.originals).length===2,'PERSIST-09 retest distinct from re-evaluation');
const newExecution=current(s).execution;
await rejects(()=>operate(s,op('binding',{...bindingPayload,execution_id:newExecution.id,question_attempt_id:newExecution.question_attempt_ids[0],human_explicit:true})),'CROSS_LINEAGE');
const cycle=structuredClone(s);cycle.executions[e.id].retest_of=e.id;await rejects(()=>validateGraph(cycle),'CYCLIC_LINEAGE');
const badResult=structuredClone(s);badResult.results[r1.id].context.question.prompt.ja='changed';await rejects(()=>validateGraph(badResult),'RESULT_CONTEXT_MISMATCH');
const badOriginal=structuredClone(s);badOriginal.originals[original.id].text='changed';await rejects(()=>validateGraph(badOriginal),'ORIGINAL_DIGEST_MISMATCH');
const old={session_id:'legacy',evidence:[{evidence_id:'old',question_id:'Q1',original_response:'原文'}],assessments:[{observed:'old free text',diff:'old reason'}]};
const preserved=legacyReference(old);
check(JSON.stringify(preserved.snapshot)===JSON.stringify(old),'MIGRATION-01 exact legacy question/evidence relation retained');
check(preserved.scope==='SCOPE_UNRECORDED'&&preserved.read_only,'MIGRATION-02 unrecorded scope never becomes WHOLE');
check(!JSON.stringify(preserved).includes('choice_set_version')&&preserved.snapshot.assessments[0].observed==='old free text','MIGRATION-03 no fabricated choices');
await run('draft',{execution_id:newExecution.id,question_attempt_id:newExecution.question_attempt_ids[0],expected_original:null,response:'unfinished draft'});
await run('view',{stage:1});
check(s.drafts.responses[newExecution.id]==='unfinished draft','UX-04 back preserves drafts');
const executionCount=Object.keys(s.executions).length;
await run('start',{question_id:'PB-JUDGE',expected_execution:newExecution.id});
check(Object.keys(s.executions).length===executionCount,'Unchanged preparation resumes same execution');
await run('prepare',{expected:s.preparation,preparation:{...s.preparation,platform:'claude'}});
check(current(s).status==='PENDING','Changed preparation does not fall back to a historical result');
await run('start',{question_id:'PB-JUDGE',expected_execution:null});
check(Object.keys(s.executions).length===executionCount+1,'Changed preparation creates new-condition attempt');
console.log(`TRAINER_UX3_CONTRACT PASS ${count}/${count}`);
