import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { EDITABLE_DENOMINATOR } from "../tools/v1/semantic-registry.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const candidates = [process.env.SAKU_CHROME_PATH, "C:/Program Files/Google/Chrome/Application/chrome.exe", "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"].filter(Boolean);
let chrome = "";
for (const candidate of candidates) { try { if ((await stat(candidate)).isFile()) { chrome = candidate; break; } } catch {} }
if (!chrome) { console.error("BUILDER_WORKFLOW NOT_AVAILABLE / CHROME_NOT_FOUND"); process.exit(2); }

const harness = `<!doctype html><meta charset="utf-8"><iframe id="builder" src="/tools/saku-builder.html" style="width:1280px;height:820px;border:0"></iframe><pre id="result" data-status="RUNNING"></pre><script type="module">
const result=document.getElementById("result"),checks=[];const check=(c,n)=>{if(!c)throw new Error(n);checks.push(n)};const wait=ms=>new Promise(r=>setTimeout(r,ms));const poll=async f=>{for(let i=0;i<120;i++){if(f())return;await wait(50)}throw new Error("builder boot timeout")};const input=(e,v)=>{e.value=v;e.dispatchEvent(new Event("input",{bubbles:true}))};const click=e=>e.dispatchEvent(new MouseEvent("click",{bubbles:true,cancelable:true}));
try{const frame=document.getElementById("builder");await new Promise(r=>frame.addEventListener("load",r,{once:true}));const w=frame.contentWindow,d=frame.contentDocument;await poll(()=>w.SAKU_FROZEN_IA&&d.documentElement.dataset.frozenIa==="five-chapter-v1");w.confirm=()=>true;
const chapters=[...d.querySelectorAll(".frozen-chapter")];check(chapters.length===5,"Frozen IA five chapters");check(chapters.map(x=>x.dataset.frozenChapter).join(",")==="identity,purpose,work,persona,boundary","Frozen IA chapter order");
const homes=[...d.querySelectorAll("[data-canonical-path]")].map(x=>x.dataset.canonicalPath);check(homes.length===${EDITABLE_DENOMINATOR}&&new Set(homes).size===${EDITABLE_DENOMINATOR},"one authoring home per editable semantic");check(d.querySelectorAll(".registry-help").length>=${EDITABLE_DENOMINATOR},"field Help complete");
const cycle=(selector,prefix)=>{const host=d.querySelector(selector),add=host.querySelector(".add input"),button=host.querySelector(".add button");input(add,prefix+"-add");click(button);let row=host.querySelector(".row:last-child"),edit=row.querySelector("input");check(edit.value===prefix+"-add",prefix+" add");input(edit,prefix+"-edit");check(d.querySelector("#yaml").textContent.includes(prefix+"-edit"),prefix+" edit reaches output");click(row.querySelector("button"));check(![...host.querySelectorAll(".row input")].some(x=>x.value===prefix+"-edit"),prefix+" remove")};
click(d.querySelector("#loadExample"));cycle('[data-list="persona_rules.values"]',"values");cycle('[data-list="unified.allowed_variation"]',"variation");click(d.querySelector("#loadExample"));cycle('[data-list="persona_rules.values"]',"replacement");
input(d.querySelector('[data-path="meta.name"]'),"Frozen workflow");check(d.querySelector("#yaml").textContent.includes("Frozen workflow"),"edit updates YAML preview");const yaml=d.querySelector("#yaml").textContent;const parsed=w.parseBuilderYaml(yaml);check(parsed.identity.display_name==="Frozen workflow","YAML reopens current Character");check(await w.importCharacterYaml(yaml)===true,"Unified YAML import accepted");
const tabs=[...d.querySelectorAll("#pvTabs button")];for(const text of ["character.yaml","Character File","Help"]){const b=tabs.find(x=>x.textContent.trim().startsWith(text));check(Boolean(b),"output tab "+text);click(b)}
const before=JSON.stringify(w.__saku_data());w.SAKU_GOLDEN_UI.setLocale("en-US");await wait(250);check(d.documentElement.lang==="en","English UI");check(JSON.stringify(w.__saku_data())===before,"UI language does not change Character data");check(d.querySelectorAll(".frozen-chapter").length===5,"English rerender preserves five chapters");
check(!d.querySelector('[data-path*="organization_participation"],[data-path*="runtime"],[data-path*="credential"],[data-path*="authority"]'),"runtime and external controls absent");check(!d.querySelector("#qsRows,#personaTest,#loadRoleCsv,#roleCsvFile"),"retired embedded helpers absent");check(d.querySelectorAll(".fixed-seat-list li").length===8,"fixed 1+7 informational");check(d.querySelectorAll(".tuning-symptom-grid button").length===20,"twenty human-symptom entries");
result.dataset.status="PASS";result.textContent=JSON.stringify({status:"PASS",passed:checks.length,checks})}catch(error){result.dataset.status="FAIL";result.textContent=JSON.stringify({status:"FAIL",passed:checks.length,error:String(error?.message||error),checks})}
</script>`;

const mime=new Map([[".html","text/html; charset=utf-8"],[".mjs","text/javascript; charset=utf-8"],[".json","application/json; charset=utf-8"],[".css","text/css; charset=utf-8"]]);
const server=createServer(async(req,res)=>{const url=new URL(req.url,"http://127.0.0.1");if(url.pathname==="/__workflow"){res.writeHead(200,{"content-type":"text/html; charset=utf-8"});res.end(harness);return}try{const target=path.resolve(ROOT,url.pathname.replace(/^\/+/,""));if(!target.startsWith(ROOT+path.sep))throw new Error("outside root");res.writeHead(200,{"content-type":mime.get(path.extname(target))||"application/octet-stream"});res.end(await readFile(target));return}catch(error){if(!res.headersSent)res.writeHead(404);res.end(String(error.message))}});await new Promise(r=>server.listen(0,"127.0.0.1",r));
const profile=await mkdtemp(path.join(tmpdir(),"saku-builder-workflow-"));const child=spawn(chrome,["--headless=new","--disable-gpu","--disable-background-networking","--no-first-run","--no-default-browser-check",`--user-data-dir=${profile}`,"--virtual-time-budget=30000","--dump-dom",`http://127.0.0.1:${server.address().port}/__workflow`],{windowsHide:true,stdio:["ignore","pipe","pipe"]});let output="",stderr="";child.stdout.on("data",x=>output+=x);child.stderr.on("data",x=>stderr+=x);await new Promise(r=>child.on("close",r));server.close();await rm(profile,{recursive:true,force:true});
const status=/data-status="([A-Z]+)"/.exec(output)?.[1]||"UNKNOWN";const body=/<pre[^>]*>([\s\S]*?)<\/pre>/.exec(output)?.[1]?.replace(/&quot;/g,'"').replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")||"";const report=JSON.parse(body||'{"status":"FAIL","error":"no report"}');if(status!=="PASS"){console.error("BUILDER_WORKFLOW FAIL");console.error(JSON.stringify(report));if(stderr)console.error(stderr.slice(-2000));process.exit(1)}console.log(`BUILDER_WORKFLOW PASS ${report.passed}/${report.passed}`);for(const item of report.checks)console.log(`  PASS ${item}`);
