import { spawn } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { createServer } from 'node:http';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const chrome='C:/Program Files/Google/Chrome/Application/chrome.exe';
const harness=`<!doctype html><meta charset="utf-8"><pre id="report">RUNNING</pre><script type="module">
import { testCharacter } from '/scripts/fixtures/trainer-ux3-character.mjs';
import { openStore, current } from '/tools/v1/trainer-ux4.mjs';
const checks=[],check=(value,label)=>{if(!value)throw new Error(label);checks.push(label);};
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const until=async fn=>{for(let i=0;i<1500;i++){if(fn())return;await wait(20);}throw new Error('TIMEOUT');};
// The store writes asynchronously (IndexedDB). Read until the expected state is
// there, instead of reading once after a fixed pause and failing under load.
const settle=async(read,predicate)=>{let value;for(let i=0;i<1500;i++){value=await read();if(predicate(value))return value;await wait(20);}return value;};
let frame,doc;const errors=[];window.addEventListener('error',event=>errors.push(event.message));
const load=async()=>{if(frame)frame.remove();frame=document.createElement('iframe');frame.style.cssText='width:1280px;height:950px';frame.src='/tools/saku-trainer.html';document.body.append(frame);await new Promise(resolve=>frame.onload=resolve);doc=frame.contentDocument;frame.contentWindow.addEventListener('error',event=>errors.push(event.message));await until(()=>doc.getElementById('stage-01')||doc.getElementById('stage-02')||doc.getElementById('stage-03'));};
const click=async(id,predicate)=>{const element=doc.getElementById(id);if(!element)throw new Error('MISSING '+id);element.click();await wait(220);if(predicate)await until(predicate);};
const change=async(id,value)=>{const element=doc.getElementById(id);element.value=value;element.dispatchEvent(new Event('change',{bubbles:true}));await wait(220);};
const input=async(id,value)=>{const element=doc.getElementById(id);element.value=value;element.dispatchEvent(new Event('input',{bubbles:true}));await wait(40);};
const choose=async(name,value,type='input')=>{const element=doc.querySelector('input[name="'+name+'"][value="'+value+'"]');element.checked=true;element.dispatchEvent(new Event(type,{bubbles:true}));await wait(90);};
const toggle=async(value,checked)=>{const element=doc.querySelector('input[name="menu-item"][value="'+value+'"]');element.checked=checked;element.dispatchEvent(new Event('change',{bubbles:true}));await wait(180);};
try{
 const character=testCharacter();localStorage.setItem('saku.workspace.active',JSON.stringify({character,identity:character.identity}));
 await load();
 check(doc.querySelectorAll('.stages li').length===3,'R4-IA three-stage orientation');
 check([...doc.querySelectorAll('#stage-01>section>h2')].map(x=>x.textContent.trim()).join('|').includes('01-1 トレーニング方法を設定する|01-2 トレーニングメニューを作成する|01-3 トレーニングを開始する'),'R4-IA-01 exactly three visible preparation subsections');
 check(!doc.getElementById('session-management')&&!doc.body.innerText.includes('01-2 セッション管理'),'R4-IA-02 independent Session section removed');
 const fieldOrder=[...doc.querySelectorAll('#training-method-fields select')].map(x=>x.id);
 check(JSON.stringify(fieldOrder)===JSON.stringify(['pick','platform','question-language','execution-mode','test-scope','saved-training']),'R4-IA-03 training-method field order exact');
 check(doc.getElementById('generated-addition')&&doc.getElementById('manual-addition'),'R4 optional generated/manual additions visible');
 check(!doc.querySelector('[name="response-binding"]')&&!doc.getElementById('bind-whole')&&!doc.getElementById('bind-partial')&&!doc.getElementById('bind-unresolved'),'R4-BIND-01 old normal binding controls absent');
 await click('generate-menu',()=>doc.querySelectorAll('input[name="menu-item"]').length===9);
 check(doc.querySelectorAll('input[name="menu-item"]').length===9,'R4-MENU-01 current <30 pool shows all authored items');
 check(!doc.getElementById('more-menu'),'R4-MENU-01 no fabricated continuation for <30 pool');
 check(doc.querySelector('.menu-detail').textContent.includes('期待される内容')&&doc.querySelector('.menu-detail').textContent.includes('見るポイント'),'R4 menu item exposes question/expected/review detail');
 const db=await openStore(),sessionId=await db.active();let state=await db.load(sessionId),generationId=state.r4.generation.generation_id,order=state.r4.generation.selected_item_ids.join('|');
 await load();state=await db.load(sessionId);check(state.r4.generation.generation_id===generationId&&state.r4.generation.selected_item_ids.join('|')===order,'R4-MENU-03 restart reopens same generation/order');
 let source=await db.create(testCharacter());source=(await db.run(source.session_id,{intent:'browser-source-generation',type:'menu-generate',payload:{expected_generation:null,seed:'source'}})).session;const sourceId=source.session_id;await db.activate(sessionId);await load();
 await change('saved-training',sourceId);await click('delete-training');check(doc.getElementById('delete-dialog').open&&doc.getElementById('delete-description').textContent.includes(sourceId)&&doc.getElementById('delete-description').textContent.includes('回答'),'R4 saved-training delete identifies exact target and counts');await click('cancel-delete');check(await db.load(sourceId),'R4 delete cancel preserves selected training');
 await change('test-scope','SAVED_TRAINING');await click('generate-menu',()=>doc.querySelectorAll('input[name="menu-item"]').length===9);state=await db.load(sessionId);check(state.r4.generation.source_training.session_id===sourceId&&Object.keys(state.results).length===0,'R4-MENU-05 saved-training source reuses menu without results/completion');
 await input('generated-source','unfinished generated draft');await wait(550);state=await db.load(sessionId);check(state.r4.optional_drafts.generated.source_response==='unfinished generated draft','R4-PERSIST-02 optional draft persisted separately');
 const evidenceBeforeClear=JSON.stringify({originals:state.originals,evaluations:state.evaluations,results:state.results});await click('clear-menu');state=await db.load(sessionId);check(state.r4.generation===null&&JSON.stringify({originals:state.originals,evaluations:state.evaluations,results:state.results})===evidenceBeforeClear,'R4-MENU-06 clear removes working menu without deleting history');check(state.r4.optional_drafts.generated.source_response==='unfinished generated draft','R4 menu clear preserves incomplete optional draft');
 await click('generate-menu',()=>doc.querySelectorAll('input[name="menu-item"]').length===9);state=await db.load(sessionId);generationId=state.r4.generation.generation_id;
 await input('manual-name','手動メニュー');await input('manual-question','人が書いた質問');await input('manual-expected','人が書いた期待');await input('manual-review','人が書いた見るポイント');await click('add-manual',()=>doc.querySelectorAll('input[name="menu-item"]').length===10);
 check(!doc.getElementById('start-training').disabled,'R4-ADD-02 valid manual item can start');
 state=await db.load(sessionId);check(state.r4.optional_drafts.generated.source_response==='unfinished generated draft','R4-ADD-03 incomplete generated draft does not block manual item');
 await input('generated-source','AI generated source');await input('generated-name','生成メニュー');await input('generated-question','生成質問');await input('generated-expected','生成期待');await input('generated-review','生成見るポイント');await click('add-generated',()=>doc.querySelectorAll('input[name="menu-item"]').length===11);
 state=await db.load(sessionId);check(Object.values(state.r4.added_items).some(item=>item.provenance.kind==='GENERATED_HUMAN_CONFIRMED'),'R4-ADD-01 generated candidate selectable only after Human-confirmed add');
 const all=[...doc.querySelectorAll('input[name="menu-item"]')].map(x=>x.value);for(const id of all)if(!['PB-SAFETY','PB-HANDOFF'].includes(id))await toggle(id,false);
 state=await settle(()=>db.load(sessionId),s=>s?.r4?.generation?.current_selected_item_ids?.length===2);check(state.r4.generation.current_selected_item_ids.length===2,'working menu selection persisted');
 await change('execution-mode','CATEGORY_BATCH');await click('start-training',()=>doc.getElementById('stage-02'));
 check(doc.defaultView.scrollY===0,'Revision 4 stage transition starts at heading');
 check(doc.querySelectorAll('#stage-menu-list input[type="radio"]').length===2,'R4-02-01 Stage 02 shows all selected menu items');
 const contextGrid=doc.getElementById('stage-menu-context'),desktopColumns=getComputedStyle(contextGrid).gridTemplateColumns.split(' ').map(parseFloat);check(desktopColumns.length===2&&desktopColumns[0]<desktopColumns[1],'OWNER-MINOR-01/02 desktop menu/detail are horizontal with narrower menu list');
 check(doc.getElementById('selected-menu-detail').innerText.includes('質問文')&&doc.getElementById('selected-menu-detail').innerText.includes('期待される内容')&&doc.getElementById('selected-menu-detail').innerText.includes('見るポイント'),'R4-02-03 selected detail always visible');
 check(doc.getElementById('copy-character')&&doc.getElementById('copy-menu')&&doc.getElementById('copy-both'),'R4-COPY three unambiguous copy actions');
 check(doc.getElementById('character-copy-text').value&&doc.getElementById('menu-copy-text').value,'R4-COPY-05 separate manual-copy fallback textareas');
 check(!doc.getElementById('menu-copy-text').value.includes('期待される内容')&&!doc.getElementById('menu-copy-text').value.includes('見るポイント'),'R4-COPY-05 normal payload does not leak evaluation target');
 const originalClipboard=frame.contentWindow.navigator.clipboard;Object.defineProperty(frame.contentWindow.navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('EXPECTED_COPY_FAILURE');}}});
 await click('copy-menu');check(doc.getElementById('copy-status').textContent.includes('手動でコピー'),'R4 manual-copy fallback is truthful on clipboard failure');
 Object.defineProperty(frame.contentWindow.navigator,'clipboard',{configurable:true,value:originalClipboard});
 await input('answer-input','preserved menu-specific draft');await wait(550);state=await db.load(sessionId);const beforeOther={executions:Object.keys(state.executions).length,originals:Object.keys(state.originals).length,bindings:Object.keys(state.bindings).length,evaluations:Object.keys(state.evaluations).length,results:Object.keys(state.results).length};await click('other-menu');state=await db.load(sessionId);check(doc.getElementById('stage-02')&&doc.activeElement?.name==='active-menu','OWNER-MINOR-04 other-menu stays in Stage 02 and focuses the menu list');check(state.drafts.responses[current(state).execution.id]==='preserved menu-specific draft','OWNER-MINOR-04 unsaved menu draft is preserved');check(JSON.stringify(beforeOther)===JSON.stringify({executions:Object.keys(state.executions).length,originals:Object.keys(state.originals).length,bindings:Object.keys(state.bindings).length,evaluations:Object.keys(state.evaluations).length,results:Object.keys(state.results).length}),'OWNER-MINOR-05 other-menu creates no execution or evidence');
 state=await db.load(sessionId);const beforeSwitch=Object.keys(state.bindings).length;const other=[...doc.querySelectorAll('input[name="active-menu"]')].find(x=>!x.checked);other.checked=true;other.dispatchEvent(new Event('change',{bubbles:true}));await wait(450);state=await db.load(sessionId);check(Object.keys(state.bindings).length===beforeSwitch,'R4-02-02 radio switching saves no Evidence');
 await input('answer-input','Native-style browser answer');await wait(500);check(doc.getElementById('save-state').textContent.includes('保存'),'response draft gets visible save state');
 await click('save-response',()=>doc.getElementById('evaluation-form'));
 state=await db.load(sessionId);let c=current(state);check(c.binding.kind==='WHOLE','R4-BIND-02 response save creates exact WHOLE');
 check(Object.keys(state.originals).length===1,'R4-BIND-03 batch Original stored once');
 check(!doc.getElementById('bind-whole')&&!doc.getElementById('bind-partial'),'normal flow remains natural without binding controls');
 await choose('conclusion','MATCH');await choose('confirmed','C01');await choose('reasons','R03');await click('evaluate-menu',()=>doc.getElementById('menu-result').querySelector('.result-conclusion'));
 state=await db.load(sessionId);c=current(state);check(c.evaluation.choices.conclusion==='MATCH'&&c.evaluation.choices.reasons.includes('R03'),'R4-EVAL-01 MATCH + too-detailed saves');
 check(doc.getElementById('stage-02')&&doc.getElementById('menu-result').innerText.includes('期待どおり'),'R4-RESULT-01 per-menu result stays inline in Stage 02');
 check(doc.getElementById('parameter-recommendation').innerText.includes('決められません'),'R4-REC insufficient deterministic mapping is explicit');
 check(doc.getElementById('character-mutation-state').innerText.includes('Character変更：0'),'R4-BOUNDARY Character mutation stays zero');
 doc.getElementById('ai-consultation').open=true;await input('consult-response','External AI proposal source');await input('candidate-target','expression_semantics.voice');await input('candidate-direction','review wording');await input('candidate-reason','candidate reason');await input('candidate-effect','possible effect');await input('candidate-caution','Human review required');await input('candidate-unresolved','exact value');await click('save-ai-candidate');
 state=await db.load(sessionId);const aiCandidate=Object.values(state.r4.consultations)[0];check(aiCandidate&&aiCandidate.review_state==='HUMAN_REVIEW_REQUIRED'&&aiCandidate.canonical_mutation===false,'R4-AI-01 consultation is only an AI proposed candidate');
 check(aiCandidate.result_id===c.result.id&&aiCandidate.evaluation_id===c.evaluation.id,'R4-AI-02 AI candidate binds exact Result/Evaluation');
 const resultsBefore=Object.keys(state.results).length;const first=[...doc.querySelectorAll('input[name="active-menu"]')].find(x=>!x.checked);first.checked=true;first.dispatchEvent(new Event('change',{bubbles:true}));await wait(450);state=await db.load(sessionId);check(Object.keys(state.results).length===resultsBefore,'opening another menu creates no Result');
 check(doc.getElementById('answer-input').readOnly&&doc.getElementById('answer-input').value==='Native-style browser answer','R4 batch second item reuses same visible Original');
 await choose('conclusion','NOT_ASSESSED');await choose('confirmed','C_NONE');await choose('reasons','R02');await click('evaluate-menu',()=>doc.getElementById('menu-result').querySelector('.result-conclusion'));
 state=await db.load(sessionId);check(Object.keys(state.originals).length===1&&Object.keys(state.results).length===2,'R4-BIND-05 second batch eval reuses Original and saves independent Result');
 await click('finish-training',()=>doc.getElementById('stage-03'));
 check(doc.querySelectorAll('[data-summary-row]').length===2,'R4-SUM-02 all selected menu statuses appear');
 check(['03-1 SAKUを修正した方がよい点','03-2 このままでよい点','03-3 追加確認が必要な点','03-4 修正候補の詳細','03-5 次にすること'].every(value=>doc.body.innerText.includes(value)),'OWNER-MINOR-06 Stage 03 uses the action-oriented five-section IA');
 check(!doc.body.innerText.includes('確認できた強み')&&!doc.body.innerText.includes('まとめの固定参照'),'OWNER-MINOR-06/07 old primary and technical labels are absent');
 check(doc.getElementById('summary-modify').innerText.includes('推測した修正先は表示しません')&&doc.getElementById('summary-needs-check').innerText.includes('修正対象をまだ特定できません'),'OWNER-MINOR-10 insufficient evidence fabricates no Builder parameter');
 check(doc.getElementById('summary-candidate-detail').innerText.includes('AI提案・未確認')&&doc.getElementById('summary-character-unchanged').innerText.includes('まだSAKU Characterは変更されていません'),'OWNER-MINOR-09/11 AI caution and Character non-mutation are clear');
 check(doc.body.innerText.includes('限られたメニュー')&&doc.body.innerText.includes('平均せず'),'R4 summary preserves limited scope and conflicts');
 state=await db.load(sessionId);const summary=state.r4.summaries[state.r4.summary_head];check(summary.result_ids.length===2&&summary.evaluation_ids.length===2,'R4-SUM-03 exact Result/Evaluation set pinned');
 doc.getElementById('summary-evidence').open=true;check(summary.result_ids.every(id=>doc.getElementById('summary-evidence').innerText.includes(id))&&summary.evaluation_ids.every(id=>doc.getElementById('summary-evidence').innerText.includes(id)),'OWNER-MINOR-12 exact internal Result/Evaluation references remain available under a plain label');
 doc.querySelector('[data-summary-menu="PB-SAFETY"]').click();await wait(450);check(doc.getElementById('stage-02')&&doc.querySelector('input[name="active-menu"][value="PB-SAFETY"]').checked,'R4 summary returns to exact menu');
 await load();state=await db.load(sessionId);check(state.r4.generation.generation_id===generationId&&state.r4.active_training.menu_item_ids.length===2,'R4-PERSIST-01 restart retains generated menu and progress');
 check(JSON.stringify(character)===JSON.stringify(testCharacter()),'R4-BOUNDARY-01 Character remains unchanged');
 await change('locale','en');check(doc.querySelector('h1').textContent==='02 Check with AI','R4-LANG-01 JA/EN stage parity');
 check(!/[\u3040-\u30ff\u4e00-\u9fff]/.test(doc.getElementById('selected-menu-detail').querySelector('h2').textContent),'R4-LANG controlled heading parity');
 frame.style.width='390px';await wait(150);check(getComputedStyle(doc.getElementById('stage-menu-context')).gridTemplateColumns.split(' ').length===1,'OWNER-MINOR-03 narrow menu/detail layout stacks vertically');check(doc.documentElement.scrollWidth<=doc.documentElement.clientWidth,'R4 narrow-window layout has no horizontal overflow');
 check(errors.filter(value=>!value.includes('EXPECTED_COPY_FAILURE')).length===0,'No browser runtime errors: '+errors.join('|'));
 document.getElementById('report').textContent=JSON.stringify({status:'PASS',passed:checks.length,checks});document.getElementById('report').dataset.status='PASS';
}catch(error){document.getElementById('report').textContent=JSON.stringify({status:'FAIL',passed:checks.length,error:String(error.stack||error),checks,body:doc?.body.innerText.slice(-3500)});document.getElementById('report').dataset.status='FAIL';}
</script>`;

const mime={'.mjs':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json'};
const server=createServer(async(request,response)=>{try{const url=new URL(request.url,'http://localhost');if(url.pathname==='/__ux4__'){response.setHeader('Content-Type','text/html;charset=utf-8');response.end(harness);return;}const file=path.resolve(ROOT,decodeURIComponent(url.pathname).replace(/^\//,''));if(!file.startsWith(ROOT+path.sep))throw new Error('outside root');response.setHeader('Content-Type',(mime[path.extname(file)]||'text/plain')+';charset=utf-8');response.end(await readFile(file));}catch{response.statusCode=404;response.end('not found');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const profile=await mkdtemp(path.join(tmpdir(),'saku-ux4-test-'));
const child=spawn(chrome,['--headless=new','--disable-gpu','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:['ignore','pipe','pipe']});
let output='',stderr='',socket;child.stderr.on('data',chunk=>stderr+=chunk);const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
 let port;for(let i=0;i<100;i++){try{port=(await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await pause(100);}}if(!port)throw new Error('Chrome control port unavailable');
 const target=await(await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`http://127.0.0.1:${server.address().port}/__ux4__`)}`,{method:'PUT'})).json();socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise(resolve=>socket.onopen=resolve);
 let sequence=0;const pending=new Map();socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.id){pending.get(data.id)?.(data);pending.delete(data.id);}};const call=(method,params={})=>new Promise(resolve=>{const id=++sequence;pending.set(id,resolve);socket.send(JSON.stringify({id,method,params}));});
 for(let i=0;i<1200;i++){const result=await call('Runtime.evaluate',{expression:'document.getElementById("report")?.dataset.status',returnByValue:true});if(result.result?.result?.value){output=(await call('Runtime.evaluate',{expression:'document.documentElement.outerHTML',returnByValue:true})).result.result.value;break;}await pause(100);}if(!output)output=(await call('Runtime.evaluate',{expression:'document.documentElement.outerHTML',returnByValue:true})).result.result.value;
}finally{socket?.close();child.kill();await new Promise(resolve=>child.exitCode!==null?resolve():child.once('exit',resolve));server.close();await rm(profile, { recursive: true, force: true, maxRetries: 20, retryDelay: 250 }).catch(error => console.warn(`CLEANUP_SKIPPED browser profile left at ${profile}: ${error?.code || error}`));}
const match=output.match(/<pre id="report" data-status="(PASS|FAIL)">([\s\S]*?)<\/pre>/);if(!match){console.error(output.slice(0,2000),stderr.slice(-1000));process.exit(1);}const report=JSON.parse(match[2].replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));console.log(JSON.stringify(report,null,2));if(report.status!=='PASS')process.exitCode=1;
